#!/bin/bash


WGET_VERSION=$(wget --version | grep -oie "wget [0-9][0-9.]*" | head -n 1 | awk '{print $2}')
if [ -z "$WGET_VERSION" ]
then
WGET_VERSION=PARSE_ERROR
fi

WGET_USER_AGENT="wget/$WGET_VERSION/gateway/4.4.16"


##############################################################################
#
# Generated by: NSF NCAR Climate Data Gateway
# Created: 2025-03-24T23:50:41-06:00
#
# Template version: 0.4.7-wget-checksum
#
#
# Your download selection includes data that might be secured using API Token based
# authentication. Therefore, this script can have your api-token. If you
# re-generate your API Token after you download this script, the download will
# fail. If that happens, you can either re-download the script or you can edit
# this script replacing the old API Token with the new one. View your API token
# by going to "Account Home":
#
# https://www.earthsystemgrid.org/account/user/account-home.html
#
# and clicking on "API Token" link under "Personal Account". You will be asked
# to log into the application before you can view your API Token.
#
#
# Dataset
# ucar.cgd.cesm2.fosi.ocn.proc.monthly_ave.SSH
# 05c62b84-e28c-470d-b44a-6ddba0743a50
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2.fosi.ocn.proc.monthly_ave.SSH.html
# https://www.earthsystemgrid.org/dataset/id/05c62b84-e28c-470d-b44a-6ddba0743a50.html
#
# Dataset Version
# 1
# 6b6a57b6-ff83-46ec-bce6-e4f45f51faaa
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2.fosi.ocn.proc.monthly_ave.SSH/version/1.html
# https://www.earthsystemgrid.org/dataset/version/id/6b6a57b6-ff83-46ec-bce6-e4f45f51faaa.html
#
##############################################################################

CACHE_FILE=.md5_results
MAX_RETRY=3


usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
}
#defaults
debug=0
clean_work=1
verbose=1

#parse flags

while getopts ':pdvqko:' OPT; do

    case $OPT in

        p) clean_work=0;;       #	: preserve data that failed checksum
        o) output="$OPTARG";;   #<file>	: Write output for DML in the given file
        d) debug=1;;            #	: display debug information
        v) verbose=1;;          #       : be more verbose
        q) quiet=1;;            #	: be less verbose
        k) cert=1;;            #	: add --no-check-certificate
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

if [[ "$output" ]]; then
    #check and prepare the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    : > "$output" || { echo "Can't write file $output"; break; }
fi

    ((debug)) && echo "debug=$debug, cert=$cert, verbose=$verbose, quiet=$quiet, clean_work=$clean_work"

##############################################################################


check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum

    case $chk_type in
        md5) local_chksum=$(md5sum "$file" | cut -f1 -d" ");;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value"
    diff -q <(echo $local_chksum) <(echo $chk_value) >/dev/null
}

download() {

    if [[ "$cert" ]]; then
      wget="wget --no-check-certificate -c --user-agent=$WGET_USER_AGENT"
    else
      wget="wget -c --user-agent=$WGET_USER_AGENT"
    fi

    ((quiet)) && wget="$wget -q" || { ((!verbose)) && wget="$wget -nv"; }

    ((debug)) && echo "wget command: $wget"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #are we just writing a file?
        if [ "$output" ]; then
            echo "$file - $url" >> $output
            echo ""
            continue
        fi

        retry_counter=0

        while : ; do
                #if we have the file, check if it's already processed.
                [ -f "$file" ] && cached="$(grep $file $CACHE_FILE)" || unset cached

                #check it wasn't modified
                if [[ -n "$cached" && "$(stat -c %Y $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    echo "Already downloaded and verified"
                    break
                fi

                # (if we had the file size, we could check before trying to complete)
                echo "Downloading"
                $wget -O "$file" $url || { failed=1; break; }

                #check if file is there
                if [[ -f "$file" ]]; then
                        ((debug)) && echo file found
                        if ! check_chksum "$file" $chksum_type $chksum; then
                                echo "  $chksum_type failed!"
                                if ((clean_work)); then
                                        rm "$file"

                                        #try again up to n times
                                        echo -n "  Re-downloading..."

                                        if [ $retry_counter -eq $MAX_RETRY]
                                        then
                                            echo "  Re-tried file $file $MAX_RETRY times...."
                                            break
                                        fi
                                        retry_counter=`expr $retry_counter + 1`

                                        continue
                                else
                                        echo "  don't use -p or remove manually."
                                fi
                        else
                                echo "  $chksum_type ok. done!"
                                echo "$file" $(stat -c %Y "$file") $chksum >> $CACHE_FILE
                        fi
                fi
                #done!
                break
        done

        if ((failed)); then
            echo "download failed"

            unset failed
        fi

    done <<EOF--dataset.file.url.chksum_type.chksum
'g.e20.G.TL319_t13.control.001.pop.h.SSH.000101-000112.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.000101-000112.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a3dac766038c55562eb2a02de222458d'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.000201-000212.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.000201-000212.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cfa0e52d2e2a84a72c90b1be2f61a358'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.000301-000312.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.000301-000312.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'aff57165399bab07eafc0abeadbf4263'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.000401-000412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.000401-000412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b0a7278395fab48022d5f7ec1b142fa3'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.000501-000512.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.000501-000512.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b4a1cd100bfb987f13b1d1e35efc97bf'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.000601-000612.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.000601-000612.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '88cd0a19beb7ae28f6c913c2ea1c659e'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.000701-000712.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.000701-000712.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '17798683d8330b205cb912d7cd0dbad8'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.000801-000812.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.000801-000812.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '16fe1cf516a128a64335010bdff9a39b'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.000901-000912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.000901-000912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c878bdfe8aa36ba91afbabbb6f42a15b'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.001001-001012.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.001001-001012.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '666627e355bfb60848eacdf111f726b1'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.001101-001112.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.001101-001112.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '463b01db7f2ffebb057e4d4da6adae19'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.001201-001212.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.001201-001212.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '20acf3898b24e9b02eff4568785c3c95'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.001301-001312.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.001301-001312.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e98fd078e36145585f0bcd9e508bbcdf'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.001401-001412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.001401-001412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9b2b0e6afad21d4baa978f3edd34d785'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.001501-001512.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.001501-001512.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '52bc694484c0d7311daa3015c3eef4a8'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.001601-001612.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.001601-001612.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f4c239cdafbab30898afa03fcbb8592b'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.001701-001712.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.001701-001712.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '32ef3a1e6e287e73a435d539c878a6c8'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.001801-001812.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.001801-001812.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e7d34da264a658bdc4a662b7a9f164e0'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.001901-001912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.001901-001912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f2e995aa7aec6a48755c68d2b9749d62'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.002001-002012.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.002001-002012.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd1c9988542ab912c72467b66d31b3aa2'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.002101-002112.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.002101-002112.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c2ff19b3e4876a43d22cd8a154cca447'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.002201-002212.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.002201-002212.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '348059b0ba514dd9421c281d618cd6a0'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.002301-002312.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.002301-002312.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '415e4b0a7ef33919eb60ab00ddb44905'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.002401-002412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.002401-002412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '07bcc973291a8761fe64e2c9c38355c0'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.002501-002512.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.002501-002512.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f611704a55fe9c342dcf4915882a8f54'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.002601-002612.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.002601-002612.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3fe2f7b9d43094470ceda82017f12da9'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.002701-002712.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.002701-002712.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7b7e8607ae040ae2defbdb154eb7f5e1'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.002801-002812.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.002801-002812.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'bacd9a6c09085353ec3131b0f0fa7367'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.002901-002912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.002901-002912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '43246560df532a3a69f085144f82fd54'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.003001-003012.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.003001-003012.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '35241cf1d26c02b0068a732beacf5ff3'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.003101-003112.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.003101-003112.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '86fc2a5059459a2193c302480f84ef46'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.003201-003212.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.003201-003212.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'df229c75a22422cb1f2bed7343faf595'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.003301-003312.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.003301-003312.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5ac8166b0d1617fd69fc5692f50fe660'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.003401-003412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.003401-003412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9c048ba8a53a9c64c5d09c39b0350175'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.003501-003512.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.003501-003512.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '857c4d8eb1955d3d7c6889d946d47809'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.003601-003612.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.003601-003612.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5451ae4f4d41fb90d753f25ccc8b75f0'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.003701-003712.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.003701-003712.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a9bf0277d16dcc92627fb24b042c0d48'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.003801-003812.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.003801-003812.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '03398901d4ddf542e8837ef97356a3bc'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.003901-003912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.003901-003912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a863c51cd0dfcc03b9973711c48b81a6'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.004001-004012.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.004001-004012.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '851eabe2394decb7f2963576e20a888a'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.004101-004112.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.004101-004112.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd892487336129c915a8ebf44301af9fa'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.004201-004212.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.004201-004212.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '235c1792468bea46955fd470bedf0451'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.004301-004312.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.004301-004312.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'baf2b9f293485f0e083137f2a094480f'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.004401-004412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.004401-004412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '79409e72b69448cc6622e9394094eb36'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.004501-004512.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.004501-004512.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e07ab65272e082265f46274ddb9118b7'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.004601-004612.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.004601-004612.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '77d6843ed8cfedd773d060ab0f510a19'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.004701-004712.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.004701-004712.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0fd49a0fc7c2a918dc153f829e297e5f'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.004801-004812.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.004801-004812.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7b5f06fe716e50f9d08819c44f80fbeb'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.004901-004912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.004901-004912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '417866fb837a1300f13ce8e3cf8c3d1c'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.005001-005012.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.005001-005012.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cb7339ba534a0ad472c00a953a403a77'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.005101-005112.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.005101-005112.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ef3c9328c773e0e6648369d41a3ffcf1'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.005201-005212.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.005201-005212.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2870e61863a3f1ea61cf87fa54576eba'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.005301-005312.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.005301-005312.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3afb08e2c553172d6ef9c168503d5627'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.005401-005412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.005401-005412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'fbc60817786eddef2f48e7c0842afca5'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.005501-005512.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.005501-005512.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '370287a279856c031473336c265096e5'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.005601-005612.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.005601-005612.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '60654dda99e88261672df85d58f1af0a'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.005701-005712.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.005701-005712.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4203c978e16d0a15409fbef2bb937ffa'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.005801-005812.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.005801-005812.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '34e8f9baf50f62bee8bee9b5e64c4f56'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.005901-005912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.005901-005912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '683f2f1d3cbb5caab69ff5475355a0c8'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.006001-006012.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.006001-006012.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'eed3b0ade662b79758e2c2119e761894'
'g.e20.G.TL319_t13.control.001.pop.h.SSH.006101-006112.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/collections/cmip/CMIP6/iHESP/FOSI/HR/g.e20.G.TL319_t13.control.001/ocn/proc/tseries/month_1/g.e20.G.TL319_t13.control.001.pop.h.SSH.006101-006112.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4a93495b1724a403f542e2de89fdc0ed'
EOF--dataset.file.url.chksum_type.chksum

}


#
# MAIN
#
echo "Running $(basename $0) version: $version"

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE

download

#remove duplicates (if any)
{ rm $CACHE_FILE && tac | awk '!x[$1]++' | tac > $CACHE_FILE; } < $CACHE_FILE

