#!/bin/bash


WGET_VERSION=$(wget --version | grep -oie "wget [0-9][0-9.]*" | head -n 1 | awk '{print $2}')
if [ -z "$WGET_VERSION" ]
then
WGET_VERSION=PARSE_ERROR
fi

WGET_USER_AGENT="wget/$WGET_VERSION/esg/4.3.2-20230405-191025/created/2023-04-11T07:43:00-06:00"


##############################################################################
#
# Climate Data Gateway download script
#
#
# Generated by: NCAR Climate Data Gateway
#
# Template version: 0.4.7-wget-checksum
#
#
# Your download selection includes data that might be secured using API Token based
# authentication. Therefore, this script can have your api-token. If you
# re-generate your API Token after you download this script, the download will
# fail. If that happens, you can either re-download this script or you can replace
# the old API Token with the new one by going to the Account Home:
#
# https://www.earthsystemgrid.org/account/user/account-home.html
#
# and clicking on "API Token" link under "Personal Account". You will be asked
# to log into the application before you can view your API Token.
#
#
# Dataset
# ucar.cgd.cesm2le.ocn.proc.monthly_ave.diatChl
# 578737d2-1a9c-4d96-9cc2-f132482bf3cd
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.ocn.proc.monthly_ave.diatChl.html
# https://www.earthsystemgrid.org/dataset/id/578737d2-1a9c-4d96-9cc2-f132482bf3cd.html
#
# Dataset Version
# 1
# 9de5e76c-845c-4691-bebe-eb6d6b79a182
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.ocn.proc.monthly_ave.diatChl/version/1.html
# https://www.earthsystemgrid.org/dataset/version/id/9de5e76c-845c-4691-bebe-eb6d6b79a182.html
#
##############################################################################

CACHE_FILE=.md5_results
MAX_RETRY=3


usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
}
#defaults
debug=0
clean_work=1
verbose=1

#parse flags

while getopts ':pdvqko:' OPT; do

    case $OPT in

        p) clean_work=0;;       #    : preserve data that failed checksum
        o) output="$OPTARG";;   #<file>    : Write output for DML in the given file
        d) debug=1;;            #    : display debug information
        v) verbose=1;;          #       : be more verbose
        q) quiet=1;;            #    : be less verbose
        k) cert=1;;            #    : add --no-check-certificate
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

if [[ "$output" ]]; then
    #check and prepare the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    : > "$output" || { echo "Can't write file $output"; break; }
fi

    ((debug)) && echo "debug=$debug, cert=$cert, verbose=$verbose, quiet=$quiet, clean_work=$clean_work"

##############################################################################


check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum

    case $chk_type in
        md5) local_chksum=$(md5sum "$file" | cut -f1 -d" ");;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value"
    diff -q <(echo $local_chksum) <(echo $chk_value) >/dev/null
}

download() {

    if [[ "$cert" ]]; then
      wget="wget --no-check-certificate -c --user-agent=$WGET_USER_AGENT"
    else
      wget="wget -c --user-agent=$WGET_USER_AGENT"
    fi

    ((quiet)) && wget="$wget -q" || { ((!verbose)) && wget="$wget -nv"; }

    ((debug)) && echo "wget command: $wget"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #are we just writing a file?
        if [ "$output" ]; then
            echo "$file - $url" >> $output
            echo ""
            continue
        fi

        retry_counter=0

        while : ; do
                #if we have the file, check if it's already processed.
                [ -f "$file" ] && cached="$(grep $file $CACHE_FILE)" || unset cached

                #check it wasn't modified
                if [[ -n "$cached" && "$(stat -c %Y $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    echo "Already downloaded and verified"
                    break
                fi

                # (if we had the file size, we could check before trying to complete)
                echo "Downloading"
                $wget -O "$file" $url || { failed=1; break; }

                #check if file is there
                if [[ -f "$file" ]]; then
                        ((debug)) && echo file found
                        if ! check_chksum "$file" $chksum_type $chksum; then
                                echo "  $chksum_type failed!"
                                if ((clean_work)); then
                                        rm "$file"

                                        #try again up to n times
                                        echo -n "  Re-downloading..."

                                        if [ $retry_counter -eq $MAX_RETRY]
                                        then
                                            echo "  Re-tried file $file $MAX_RETRY times...."
                                            break
                                        fi
                                        retry_counter=`expr $retry_counter + 1`

                                        continue
                                else
                                        echo "  don't use -p or remove manually."
                                fi
                        else
                                echo "  $chksum_type ok. done!"
                                echo "$file" $(stat -c %Y "$file") $chksum >> $CACHE_FILE
                        fi
                fi
                #done!
                break
        done

        if ((failed)); then
            echo "download failed"

            unset failed
        fi

    done <<EOF--dataset.file.url.chksum_type.chksum
'b.e21.BSSP370cmip6.f09_g17.LE2-1001.001.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1001.001.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f192b173794f41bda533582a10edce39'
'b.e21.BSSP370cmip6.f09_g17.LE2-1021.002.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1021.002.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2dce8f1c7e1e69d2dfa178025f18f596'
'b.e21.BSSP370cmip6.f09_g17.LE2-1041.003.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1041.003.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f64c6d2bd4731f85f82446a7cb65b8fe'
'b.e21.BSSP370cmip6.f09_g17.LE2-1061.004.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1061.004.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0d7aec89f544720ea7273da1c8227d56'
'b.e21.BSSP370cmip6.f09_g17.LE2-1081.005.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1081.005.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4422f37c74d4dad8b29081cb30f04f72'
'b.e21.BSSP370cmip6.f09_g17.LE2-1101.006.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1101.006.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'adba8c9883fdfaff2ba36e019a4e122d'
'b.e21.BSSP370cmip6.f09_g17.LE2-1121.007.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1121.007.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0e7670267762494aec20aef6d81297ff'
'b.e21.BSSP370cmip6.f09_g17.LE2-1141.008.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1141.008.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '041900185c87b4cfd6eea62662639eb7'
'b.e21.BSSP370cmip6.f09_g17.LE2-1161.009.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1161.009.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2363c80f8838d1df2d69ee5f6d57b956'
'b.e21.BSSP370cmip6.f09_g17.LE2-1181.010.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1181.010.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8529dca29408c95e6d6d16bce006de90'
'b.e21.BSSP370cmip6.f09_g17.LE2-1231.001.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1231.001.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '681334c99de73c2841657e91f08c230f'
'b.e21.BSSP370cmip6.f09_g17.LE2-1231.002.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1231.002.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9903b12215087a3af5ec40050f1696a6'
'b.e21.BSSP370cmip6.f09_g17.LE2-1231.003.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1231.003.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4c3817b47f2b85672234c93b2439906c'
'b.e21.BSSP370cmip6.f09_g17.LE2-1231.004.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1231.004.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7a00e56fe7d147e6fe06d3235d39c192'
'b.e21.BSSP370cmip6.f09_g17.LE2-1231.005.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1231.005.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '848c915bbc310cf72db76f9373ed5802'
'b.e21.BSSP370cmip6.f09_g17.LE2-1231.006.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1231.006.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '66f725f0d588153f9f3d56665d139a2f'
'b.e21.BSSP370cmip6.f09_g17.LE2-1231.007.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1231.007.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '062a2a7851e7780ab4d211536b1c4843'
'b.e21.BSSP370cmip6.f09_g17.LE2-1231.008.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1231.008.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '256f96ff052bbe358f46bb8593322d20'
'b.e21.BSSP370cmip6.f09_g17.LE2-1231.009.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1231.009.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6b64c31b48054e13cfe899cf373e2ab6'
'b.e21.BSSP370cmip6.f09_g17.LE2-1231.010.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1231.010.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '70c5c921e983f800a5b2631aa1151a33'
'b.e21.BSSP370cmip6.f09_g17.LE2-1251.001.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1251.001.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e3554c92014bcbeb19b9a8f4fa96d5ff'
'b.e21.BSSP370cmip6.f09_g17.LE2-1251.002.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1251.002.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f1f0c7458ef0a29b190bbbe8312a579a'
'b.e21.BSSP370cmip6.f09_g17.LE2-1251.003.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1251.003.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '85f6178dd87def90bd63930992aee814'
'b.e21.BSSP370cmip6.f09_g17.LE2-1251.004.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1251.004.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '311303afc978ae7489d733a42d5b4276'
'b.e21.BSSP370cmip6.f09_g17.LE2-1251.005.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1251.005.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd0035067ec24175eab7e2724380afee1'
'b.e21.BSSP370cmip6.f09_g17.LE2-1251.006.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1251.006.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f28cbac14ba3fb77158be94566d73d2f'
'b.e21.BSSP370cmip6.f09_g17.LE2-1251.007.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1251.007.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '62bc5e55b3ebd873c8dc9e39914854a5'
'b.e21.BSSP370cmip6.f09_g17.LE2-1251.008.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1251.008.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a280bd86f0ab532ea12fe684c1563628'
'b.e21.BSSP370cmip6.f09_g17.LE2-1251.009.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1251.009.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9752b9d3fc75a70fd33481e3fa26e76b'
'b.e21.BSSP370cmip6.f09_g17.LE2-1251.010.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1251.010.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd045e10b0b16025f4e3ebcb207f25ea9'
'b.e21.BSSP370cmip6.f09_g17.LE2-1281.001.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1281.001.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '89715a84eab2cd0616eef045fbc03875'
'b.e21.BSSP370cmip6.f09_g17.LE2-1281.002.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1281.002.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '110a7dc0ab1923955c7b5c6ffdf3a7a8'
'b.e21.BSSP370cmip6.f09_g17.LE2-1281.003.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1281.003.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a6b51890a578738e503979fa64b4e8f1'
'b.e21.BSSP370cmip6.f09_g17.LE2-1281.004.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1281.004.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '50360a713dd256ba90edf76fb34533e4'
'b.e21.BSSP370cmip6.f09_g17.LE2-1281.005.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1281.005.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1b3581d52d1680468a356b77b47bd76b'
'b.e21.BSSP370cmip6.f09_g17.LE2-1281.006.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1281.006.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b211f3bfaae0b40efc7414cfe3715aaa'
'b.e21.BSSP370cmip6.f09_g17.LE2-1281.007.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1281.007.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '657264f91aa03c4cebdb58c9c675f4cc'
'b.e21.BSSP370cmip6.f09_g17.LE2-1281.008.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1281.008.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e69b1048f0d5cb99ec0b1031724ba033'
'b.e21.BSSP370cmip6.f09_g17.LE2-1281.009.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1281.009.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1f96eb11a13a0633ffc979779afb1972'
'b.e21.BSSP370cmip6.f09_g17.LE2-1281.010.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1281.010.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '82e1267b6098dc71137dded9334c4b26'
'b.e21.BSSP370cmip6.f09_g17.LE2-1301.001.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1301.001.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '02ee58717efb0636c59638f545199c71'
'b.e21.BSSP370cmip6.f09_g17.LE2-1301.002.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1301.002.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c736de2cd173a6c7abc9a6c3e4b1faf1'
'b.e21.BSSP370cmip6.f09_g17.LE2-1301.003.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1301.003.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '387d9d41edca55582922d7f11b10b9b4'
'b.e21.BSSP370cmip6.f09_g17.LE2-1301.004.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1301.004.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '69d751712ec4e445d2ce766df126e92a'
'b.e21.BSSP370cmip6.f09_g17.LE2-1301.005.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1301.005.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '82297f4b0deee3216c3655213213859f'
'b.e21.BSSP370cmip6.f09_g17.LE2-1301.006.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1301.006.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e544b3ac0f276ad31854ca5706aa7856'
'b.e21.BSSP370cmip6.f09_g17.LE2-1301.007.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1301.007.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '28d06cbbe4e43e57d7215b72a083d3f0'
'b.e21.BSSP370cmip6.f09_g17.LE2-1301.008.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1301.008.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a665d369c776aeb42cac9991bee0d923'
'b.e21.BSSP370cmip6.f09_g17.LE2-1301.009.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1301.009.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e4781d0e7da8769bbc1c0262e4ee0fec'
'b.e21.BSSP370cmip6.f09_g17.LE2-1301.010.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370cmip6.f09_g17.LE2-1301.010.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1ef8025a768f8b85adfbe22f5afe60d9'
'b.e21.BSSP370smbb.f09_g17.LE2-1011.001.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1011.001.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a70bbec365dbc4937e432c895648a07d'
'b.e21.BSSP370smbb.f09_g17.LE2-1031.002.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1031.002.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '30b2277ad4c915f05c20e15c424963ff'
'b.e21.BSSP370smbb.f09_g17.LE2-1051.003.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1051.003.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6b44c7fb9d388bc1a99b2ee8cd3da7ef'
'b.e21.BSSP370smbb.f09_g17.LE2-1071.004.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1071.004.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ac5a982a966644e17a96d778a3fcad0f'
'b.e21.BSSP370smbb.f09_g17.LE2-1091.005.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1091.005.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '19f7dcb6106fcb6c6abc6d47d52b0347'
'b.e21.BSSP370smbb.f09_g17.LE2-1111.006.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1111.006.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '429a2af3cd088efaf04aec05a2984077'
'b.e21.BSSP370smbb.f09_g17.LE2-1131.007.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1131.007.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a17512a785caaaafc3fc7d0791e004ce'
'b.e21.BSSP370smbb.f09_g17.LE2-1151.008.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1151.008.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd282dcf7e4b2b516fb61265ba00eafb2'
'b.e21.BSSP370smbb.f09_g17.LE2-1171.009.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1171.009.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '507dc59877035996b10785710955068e'
'b.e21.BSSP370smbb.f09_g17.LE2-1191.010.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1191.010.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '031445c697177ab6c6a5cb576c0e9e75'
'b.e21.BSSP370smbb.f09_g17.LE2-1231.011.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1231.011.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '78b587cb1006c31f5f679f5db677c2c2'
'b.e21.BSSP370smbb.f09_g17.LE2-1231.012.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1231.012.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c0915ed60b5a5c8db76dc062feff50fb'
'b.e21.BSSP370smbb.f09_g17.LE2-1231.013.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1231.013.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '212748a2a96b57ab702ba3b15a03016e'
'b.e21.BSSP370smbb.f09_g17.LE2-1231.014.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1231.014.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd41694794db41c95fb7bd6ff86085871'
'b.e21.BSSP370smbb.f09_g17.LE2-1231.015.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1231.015.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '75101a6d94c07f1006f5fb7bba67e304'
'b.e21.BSSP370smbb.f09_g17.LE2-1231.016.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1231.016.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5087b5a7221295763a365eedc649aa9c'
'b.e21.BSSP370smbb.f09_g17.LE2-1231.017.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1231.017.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '08370b4a56b1e56a44d9fc42376a4027'
'b.e21.BSSP370smbb.f09_g17.LE2-1231.018.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1231.018.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '58010680398e10f7e14541f3837e29c6'
'b.e21.BSSP370smbb.f09_g17.LE2-1231.019.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1231.019.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'dcc7f62115115639414234d59437d657'
'b.e21.BSSP370smbb.f09_g17.LE2-1231.020.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1231.020.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1b8cb45a6fb78eabc4cfe7b82697bbdd'
'b.e21.BSSP370smbb.f09_g17.LE2-1251.011.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1251.011.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '414af5056baaaca1ab172c2f297979ec'
'b.e21.BSSP370smbb.f09_g17.LE2-1251.012.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1251.012.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '249ebcfe368a374ee2be17a566668df7'
'b.e21.BSSP370smbb.f09_g17.LE2-1251.013.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1251.013.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f797e67bc7f75c2a2f388d311fb1d658'
'b.e21.BSSP370smbb.f09_g17.LE2-1251.014.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1251.014.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f1dd5ca6024433ebdf29c51fb30e3bc5'
'b.e21.BSSP370smbb.f09_g17.LE2-1251.015.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1251.015.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '69dc5d8945bc70ea838e33263f42f7e7'
'b.e21.BSSP370smbb.f09_g17.LE2-1251.016.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1251.016.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e100a56c568d4867fa45184f92a637c3'
'b.e21.BSSP370smbb.f09_g17.LE2-1251.017.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1251.017.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0cde0cae69e2f02534c2ad31fae723fb'
'b.e21.BSSP370smbb.f09_g17.LE2-1251.018.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1251.018.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9fe4974c564ccae186d3b93e19cded84'
'b.e21.BSSP370smbb.f09_g17.LE2-1251.019.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1251.019.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a0e289dd040445b874210ed99b7b62ce'
'b.e21.BSSP370smbb.f09_g17.LE2-1251.020.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1251.020.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a549064cb41c18862952dcba184c8f06'
'b.e21.BSSP370smbb.f09_g17.LE2-1281.011.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1281.011.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2dc0a43a39588f8aea2026375e8d6b68'
'b.e21.BSSP370smbb.f09_g17.LE2-1281.012.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1281.012.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4410c6edad3c18d319a22f801ffeb664'
'b.e21.BSSP370smbb.f09_g17.LE2-1281.013.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1281.013.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5144b94944140a4828b19f679ddd08e4'
'b.e21.BSSP370smbb.f09_g17.LE2-1281.014.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1281.014.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5dda7e0547d11c3b150535b684074f73'
'b.e21.BSSP370smbb.f09_g17.LE2-1281.015.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1281.015.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8b580fefbd107e838a3eb72c8fbd701f'
'b.e21.BSSP370smbb.f09_g17.LE2-1281.016.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1281.016.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '653eab7bfe2e2804a5236ccea74e9a29'
'b.e21.BSSP370smbb.f09_g17.LE2-1281.017.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1281.017.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ad63f2822f11e06a479c6b41e6b09ce3'
'b.e21.BSSP370smbb.f09_g17.LE2-1281.018.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1281.018.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4d4849ebdf9d7ba90c396acb5d4dfd1f'
'b.e21.BSSP370smbb.f09_g17.LE2-1281.019.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1281.019.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'bc82e95edcbbfcbad09a226efc00b1be'
'b.e21.BSSP370smbb.f09_g17.LE2-1281.020.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1281.020.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5a7c262f12d57760b84b1b746aff5243'
'b.e21.BSSP370smbb.f09_g17.LE2-1301.011.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1301.011.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '56d36bd5c8dace3f81fb56e755497556'
'b.e21.BSSP370smbb.f09_g17.LE2-1301.012.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1301.012.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '76150bf8711b7e694284a7f64189d61f'
'b.e21.BSSP370smbb.f09_g17.LE2-1301.013.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1301.013.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5e70deb75de69011d64ab7709765d435'
'b.e21.BSSP370smbb.f09_g17.LE2-1301.014.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1301.014.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c7b8fc6ec1d0918bcb380f7321ab3e26'
'b.e21.BSSP370smbb.f09_g17.LE2-1301.015.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1301.015.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e25dd3fbaaf13121444f71661b6a3179'
'b.e21.BSSP370smbb.f09_g17.LE2-1301.016.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1301.016.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0f2b293bfbc7239953c85b2343dab10a'
'b.e21.BSSP370smbb.f09_g17.LE2-1301.017.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1301.017.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5ff9d2be2a004c386dc7149558c11124'
'b.e21.BSSP370smbb.f09_g17.LE2-1301.018.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1301.018.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '12d37483253f367fa460e5dfb823bfc0'
'b.e21.BSSP370smbb.f09_g17.LE2-1301.019.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1301.019.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cb103d2f5491e6cd1686772234f1a8c2'
'b.e21.BSSP370smbb.f09_g17.LE2-1301.020.pop.h.diatChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BSSP370smbb.f09_g17.LE2-1301.020.pop.h.diatChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a4c1d8b84203ff4cf43805d74f3cafcf'
EOF--dataset.file.url.chksum_type.chksum

}


#
# MAIN
#
echo "Running $(basename $0) version: $version"

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE

download

#remove duplicates (if any)
{ rm $CACHE_FILE && tac | awk '!x[$1]++' | tac > $CACHE_FILE; } < $CACHE_FILE

