#!/bin/bash


WGET_VERSION=$(wget --version | grep -oie "wget [0-9][0-9.]*" | head -n 1 | awk '{print $2}')
if [ -z "$WGET_VERSION" ]
then
WGET_VERSION=PARSE_ERROR
fi

WGET_USER_AGENT="wget/$WGET_VERSION/esg/4.3.2-20230405-191025/created/2023-04-17T03:10:29-06:00"


##############################################################################
#
# Climate Data Gateway download script
#
#
# Generated by: NCAR Climate Data Gateway
#
# Template version: 0.4.7-wget-checksum
#
#
# Your download selection includes data that might be secured using API Token based
# authentication. Therefore, this script can have your api-token. If you
# re-generate your API Token after you download this script, the download will
# fail. If that happens, you can either re-download this script or you can replace
# the old API Token with the new one by going to the Account Home:
#
# https://www.earthsystemgrid.org/account/user/account-home.html
#
# and clicking on "API Token" link under "Personal Account". You will be asked
# to log into the application before you can view your API Token.
#
#
# Dataset
# ucar.cgd.cesm2le.ocn.proc.monthly_ave.diatChl
# 578737d2-1a9c-4d96-9cc2-f132482bf3cd
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.ocn.proc.monthly_ave.diatChl.html
# https://www.earthsystemgrid.org/dataset/id/578737d2-1a9c-4d96-9cc2-f132482bf3cd.html
#
# Dataset Version
# 1
# 9de5e76c-845c-4691-bebe-eb6d6b79a182
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.ocn.proc.monthly_ave.diatChl/version/1.html
# https://www.earthsystemgrid.org/dataset/version/id/9de5e76c-845c-4691-bebe-eb6d6b79a182.html
#
##############################################################################

CACHE_FILE=.md5_results
MAX_RETRY=3


usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
}
#defaults
debug=0
clean_work=1
verbose=1

#parse flags

while getopts ':pdvqko:' OPT; do

    case $OPT in

        p) clean_work=0;;       #	: preserve data that failed checksum
        o) output="$OPTARG";;   #<file>	: Write output for DML in the given file
        d) debug=1;;            #	: display debug information
        v) verbose=1;;          #       : be more verbose
        q) quiet=1;;            #	: be less verbose
        k) cert=1;;            #	: add --no-check-certificate
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

if [[ "$output" ]]; then
    #check and prepare the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    : > "$output" || { echo "Can't write file $output"; break; }
fi

    ((debug)) && echo "debug=$debug, cert=$cert, verbose=$verbose, quiet=$quiet, clean_work=$clean_work"

##############################################################################


check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum

    case $chk_type in
        md5) local_chksum=$(md5sum "$file" | cut -f1 -d" ");;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value"
    diff -q <(echo $local_chksum) <(echo $chk_value) >/dev/null
}

download() {

    if [[ "$cert" ]]; then
      wget="wget --no-check-certificate -c --user-agent=$WGET_USER_AGENT"
    else
      wget="wget -c --user-agent=$WGET_USER_AGENT"
    fi

    ((quiet)) && wget="$wget -q" || { ((!verbose)) && wget="$wget -nv"; }

    ((debug)) && echo "wget command: $wget"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #are we just writing a file?
        if [ "$output" ]; then
            echo "$file - $url" >> $output
            echo ""
            continue
        fi

        retry_counter=0

        while : ; do
                #if we have the file, check if it's already processed.
                [ -f "$file" ] && cached="$(grep $file $CACHE_FILE)" || unset cached

                #check it wasn't modified
                if [[ -n "$cached" && "$(stat -c %Y $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    echo "Already downloaded and verified"
                    break
                fi

                # (if we had the file size, we could check before trying to complete)
                echo "Downloading"
                $wget -O "$file" $url || { failed=1; break; }

                #check if file is there
                if [[ -f "$file" ]]; then
                        ((debug)) && echo file found
                        if ! check_chksum "$file" $chksum_type $chksum; then
                                echo "  $chksum_type failed!"
                                if ((clean_work)); then
                                        rm "$file"

                                        #try again up to n times
                                        echo -n "  Re-downloading..."

                                        if [ $retry_counter -eq $MAX_RETRY]
                                        then
                                            echo "  Re-tried file $file $MAX_RETRY times...."
                                            break
                                        fi
                                        retry_counter=`expr $retry_counter + 1`

                                        continue
                                else
                                        echo "  don't use -p or remove manually."
                                fi
                        else
                                echo "  $chksum_type ok. done!"
                                echo "$file" $(stat -c %Y "$file") $chksum >> $CACHE_FILE
                        fi
                fi
                #done!
                break
        done

        if ((failed)); then
            echo "download failed"

            unset failed
        fi

    done <<EOF--dataset.file.url.chksum_type.chksum
'b.e21.BHISTsmbb.f09_g17.LE2-1011.001.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1011.001.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd3b17a5b719ebd5b9cd3301458f44631'
'b.e21.BHISTsmbb.f09_g17.LE2-1031.002.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1031.002.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '899d332e58059c472a93c196a99713ae'
'b.e21.BHISTsmbb.f09_g17.LE2-1051.003.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1051.003.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8520c6e1271974943c11211f85fcaa3b'
'b.e21.BHISTsmbb.f09_g17.LE2-1071.004.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1071.004.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3dfe7018dc48278d382258f17e6376ed'
'b.e21.BHISTsmbb.f09_g17.LE2-1091.005.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1091.005.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd1cb921f3d6aea484d625108c4611a83'
'b.e21.BHISTsmbb.f09_g17.LE2-1111.006.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1111.006.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ab055e5969bf589ce0f5fa5aad60112a'
'b.e21.BHISTsmbb.f09_g17.LE2-1131.007.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1131.007.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b0fa804f7514edc88f2cf57d7ed0c1fc'
'b.e21.BHISTsmbb.f09_g17.LE2-1151.008.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1151.008.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3859462dfed13099463ffc056efad095'
'b.e21.BHISTsmbb.f09_g17.LE2-1171.009.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1171.009.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '474f6f2379cca8ab36d9aad73368c4c9'
'b.e21.BHISTsmbb.f09_g17.LE2-1191.010.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1191.010.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3bd1747744405e4dbad0eed072746e0f'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.011.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.011.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '679c7085795b6d3992a8c2b53dd3ab67'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.012.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.012.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0fced09890ea70e564aef21983936cdb'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.013.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.013.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b9aad4002fffccf9b63e7b91df640e9a'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.014.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.014.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e1af3801fe5cc4f2fe1b2be84b7e2aeb'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.015.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.015.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9d4ee912e4a7412a3f0bd830ba06eac1'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.016.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.016.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'af6517f1cf55738607583962a17a4d11'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.017.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.017.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2f07e057129d8fbef825f50d9da307d8'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.018.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.018.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'dc97d0179b18fee33e33597b7b23e2c3'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.019.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.019.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '322b3f70cf699c1b3fb0df0bb98631c6'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.020.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.020.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a7079d763c9888ba4dffffff0b8626d3'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.011.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.011.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c0d52cde1b3bfefc414208f2b613653c'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.012.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.012.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '251f90d90add13b16789cdbca9b9bb9f'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.013.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.013.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '92813a432126978bd99c2a1bd0d0bf31'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.014.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.014.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ee95d44b876d7bbda7a8a4726449b7aa'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.015.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.015.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e567a58a65292f13aba4130b75b352dc'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.016.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.016.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3e5c241fdfe8c44625e08a3d52d8ad13'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.017.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.017.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a1edd5422c44187d1b85f333c93a2d8c'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.018.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.018.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2b5f8ec8c631782572920fafe78bc778'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.019.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.019.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3bed0a6740842fd048d4bfb08fed2301'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.020.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.020.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'accc101096a5e3621e7c6b6cd2e91fbd'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.011.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.011.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '88ff9210fcb581f3ed8bd2b4b0cc6436'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.012.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.012.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0d9a77e8aa48dbfdc7e5aba9bf9b86f3'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.013.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.013.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7f4620c82fa6e8bb7375d919e1f987cc'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.014.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.014.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '20c7418d0b60fcad6054a3ac26b459cd'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.015.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.015.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'fd6df34d12d15ec43139027151d2b40c'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.016.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.016.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '53c318d0b6b0e075b2d064490d40e9a2'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.017.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.017.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1dacf19e5342b70df4d125a5061b5e52'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.018.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.018.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ce3311d4c24ec90f507b9aa5f0335b7b'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.019.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.019.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4898d264f007490ea9883287586a5440'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.020.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.020.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'adb32c39d984851bf89eefcdcda54084'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.011.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.011.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7bf588e2f8d3c5d53cdb0fe747b00e88'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.012.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.012.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cd11ab33a60134a313e1ca81fb881937'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.013.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.013.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c9f969c4b062477ce1d47daa7e677c90'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.014.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.014.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '035b7a3a97935bec9d8026f9ae7e4b12'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.015.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.015.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ef8a475ece8c31f3bd481ae8e972fa1b'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.016.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.016.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a10ee661f901aaa8176375dfb64ebe12'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.017.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.017.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0b167dbc76156146d14e40959dabf10c'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.018.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.018.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'abd077d0b3bdaca1760dd88075a1b7de'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.019.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.019.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9a87aa807852716f9f4af02592d19811'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.020.pop.h.diatChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.020.pop.h.diatChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'faaae8302cffb02573d8ae39c252750f'
EOF--dataset.file.url.chksum_type.chksum

}


#
# MAIN
#
echo "Running $(basename $0) version: $version"

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE

download

#remove duplicates (if any)
{ rm $CACHE_FILE && tac | awk '!x[$1]++' | tac > $CACHE_FILE; } < $CACHE_FILE
