#!/bin/bash


WGET_VERSION=$(wget --version | grep -oie "wget [0-9][0-9.]*" | head -n 1 | awk '{print $2}')
if [ -z "$WGET_VERSION" ]
then
WGET_VERSION=PARSE_ERROR
fi

WGET_USER_AGENT="wget/$WGET_VERSION/esg/4.3.2-20230405-191025/created/2023-04-11T07:42:24-06:00"


##############################################################################
#
# Climate Data Gateway download script
#
#
# Generated by: NCAR Climate Data Gateway
#
# Template version: 0.4.7-wget-checksum
#
#
# Your download selection includes data that might be secured using API Token based
# authentication. Therefore, this script can have your api-token. If you
# re-generate your API Token after you download this script, the download will
# fail. If that happens, you can either re-download this script or you can replace
# the old API Token with the new one by going to the Account Home:
#
# https://www.earthsystemgrid.org/account/user/account-home.html
#
# and clicking on "API Token" link under "Personal Account". You will be asked
# to log into the application before you can view your API Token.
#
#
# Dataset
# ucar.cgd.cesm2le.ocn.proc.monthly_ave.diatChl
# 578737d2-1a9c-4d96-9cc2-f132482bf3cd
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.ocn.proc.monthly_ave.diatChl.html
# https://www.earthsystemgrid.org/dataset/id/578737d2-1a9c-4d96-9cc2-f132482bf3cd.html
#
# Dataset Version
# 1
# 9de5e76c-845c-4691-bebe-eb6d6b79a182
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.ocn.proc.monthly_ave.diatChl/version/1.html
# https://www.earthsystemgrid.org/dataset/version/id/9de5e76c-845c-4691-bebe-eb6d6b79a182.html
#
##############################################################################

CACHE_FILE=.md5_results
MAX_RETRY=3


usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
}
#defaults
debug=0
clean_work=1
verbose=1

#parse flags

while getopts ':pdvqko:' OPT; do

    case $OPT in

        p) clean_work=0;;       #    : preserve data that failed checksum
        o) output="$OPTARG";;   #<file>    : Write output for DML in the given file
        d) debug=1;;            #    : display debug information
        v) verbose=1;;          #       : be more verbose
        q) quiet=1;;            #    : be less verbose
        k) cert=1;;            #    : add --no-check-certificate
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

if [[ "$output" ]]; then
    #check and prepare the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    : > "$output" || { echo "Can't write file $output"; break; }
fi

    ((debug)) && echo "debug=$debug, cert=$cert, verbose=$verbose, quiet=$quiet, clean_work=$clean_work"

##############################################################################


check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum

    case $chk_type in
        md5) local_chksum=$(md5sum "$file" | cut -f1 -d" ");;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value"
    diff -q <(echo $local_chksum) <(echo $chk_value) >/dev/null
}

download() {

    if [[ "$cert" ]]; then
      wget="wget --no-check-certificate -c --user-agent=$WGET_USER_AGENT"
    else
      wget="wget -c --user-agent=$WGET_USER_AGENT"
    fi

    ((quiet)) && wget="$wget -q" || { ((!verbose)) && wget="$wget -nv"; }

    ((debug)) && echo "wget command: $wget"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #are we just writing a file?
        if [ "$output" ]; then
            echo "$file - $url" >> $output
            echo ""
            continue
        fi

        retry_counter=0

        while : ; do
                #if we have the file, check if it's already processed.
                [ -f "$file" ] && cached="$(grep $file $CACHE_FILE)" || unset cached

                #check it wasn't modified
                if [[ -n "$cached" && "$(stat -c %Y $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    echo "Already downloaded and verified"
                    break
                fi

                # (if we had the file size, we could check before trying to complete)
                echo "Downloading"
                $wget -O "$file" $url || { failed=1; break; }

                #check if file is there
                if [[ -f "$file" ]]; then
                        ((debug)) && echo file found
                        if ! check_chksum "$file" $chksum_type $chksum; then
                                echo "  $chksum_type failed!"
                                if ((clean_work)); then
                                        rm "$file"

                                        #try again up to n times
                                        echo -n "  Re-downloading..."

                                        if [ $retry_counter -eq $MAX_RETRY]
                                        then
                                            echo "  Re-tried file $file $MAX_RETRY times...."
                                            break
                                        fi
                                        retry_counter=`expr $retry_counter + 1`

                                        continue
                                else
                                        echo "  don't use -p or remove manually."
                                fi
                        else
                                echo "  $chksum_type ok. done!"
                                echo "$file" $(stat -c %Y "$file") $chksum >> $CACHE_FILE
                        fi
                fi
                #done!
                break
        done

        if ((failed)); then
            echo "download failed"

            unset failed
        fi

    done <<EOF--dataset.file.url.chksum_type.chksum
'b.e21.BHISTcmip6.f09_g17.LE2-1001.001.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1001.001.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd270db92d32a4920031c96329b03b90d'
'b.e21.BHISTcmip6.f09_g17.LE2-1021.002.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1021.002.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3b4d8b7685b7ff98cfb827a74f954385'
'b.e21.BHISTcmip6.f09_g17.LE2-1041.003.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1041.003.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '418bc2bc0b1e9a749df41bbe8b4aa0d6'
'b.e21.BHISTcmip6.f09_g17.LE2-1061.004.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1061.004.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '55b4ad6ea999503c266a4ddd28c1efbb'
'b.e21.BHISTcmip6.f09_g17.LE2-1081.005.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1081.005.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '11454d099961809f6d588d5052559853'
'b.e21.BHISTcmip6.f09_g17.LE2-1101.006.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1101.006.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a6fb6666578a3a4a3e855237ca522489'
'b.e21.BHISTcmip6.f09_g17.LE2-1121.007.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1121.007.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '41f7645af0bdc76e1fca8da7240cc2f0'
'b.e21.BHISTcmip6.f09_g17.LE2-1141.008.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1141.008.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e208d68ef60567511a1876f03312f0c2'
'b.e21.BHISTcmip6.f09_g17.LE2-1161.009.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1161.009.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6bb0c085cccce22d50dec06ceade28c8'
'b.e21.BHISTcmip6.f09_g17.LE2-1181.010.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1181.010.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '32e130d5ae8ad4f718f5fcb27ba3c4d6'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.001.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.001.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '317a6b966d9a4739a540fe76775535a1'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.002.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.002.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1fe4067711d1d0ea46aa918d2f17ddea'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.003.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.003.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f9d64f1ca8ae587f0f0ed0c7d75d2da1'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.004.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.004.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3d5ee371f1f0236393aa2e26e6168b31'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.005.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.005.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1e653fce2ef42f0f5457166932e74441'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.006.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.006.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5d5a83303174939ff5a454521c52395f'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.007.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.007.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8c183381dd10812289af70ad142c3a0e'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.008.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.008.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1861ade595e58ae4fad6754fc92537db'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.009.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.009.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1603be5ce580412f7721ad938ae5386c'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.010.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.010.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '96ff73bc5a46a9d4f0842879bd79d6e0'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.001.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.001.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '52672da78e80eda0ea0ae0708cfa4708'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.002.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.002.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f2f7e00b4e715c397252350421316b9a'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.003.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.003.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '38bebaad379603772eb693f293fa62e6'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.004.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.004.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '54fcbb52589a8c504b1de2a2832b9e3c'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.005.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.005.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9f6b3cef41284c0bd67f68125bb38807'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.006.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.006.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '682d41c9e4c894fd4e74e3bd5f4fe803'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.007.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.007.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd250461f72e05156d0590fa81aaff767'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.008.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.008.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e88afb9904ac4ab46c6e7dabb8956f56'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.009.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.009.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9fa8d64ef7de9b2f23ca27d8cd42237d'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.010.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.010.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6f7577b90434cb37ba7fd831f7b6b492'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.001.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.001.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '65480c80e3b0793a76a1641ba1c73702'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.002.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.002.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7b73f49ae6a73c426eb4b4186140eb15'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.003.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.003.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f2e93474af0133fd7c0c582eae425bad'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.004.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.004.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e591fd61b7cbbf6eeb541f803e4c1fad'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.005.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.005.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'fb411b313d0e03a623bed6feddbb45da'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.006.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.006.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e8f5ce3e887aa5a849b1dc06ad15db50'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.007.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.007.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '974d4321b0f8489998d7521cdb084830'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.008.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.008.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '395f7f7f372a36c2ff3ed2bd54850427'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.009.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.009.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd189e329d5a14a9152b9142b43b59fa4'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.010.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.010.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e74ba1d5ba4935ff648f82d51e665fda'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.001.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.001.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4f46786fb9325f8128ac986f06de7f50'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.002.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.002.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b0018f037e90989a19683e6af75b844e'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.003.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.003.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6a9aa37791da48677e07ea9559ce7667'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.004.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.004.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '63ce7aa2a4f7c51185730bb51cfb53a2'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.005.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.005.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3fc0ab6b6a085f97b25a3e996a4baf21'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.006.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.006.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3dbc3c3d42516f58685435fcbdf7b366'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.007.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.007.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ceb6e489eea702734c49d379ad6b2783'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.008.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.008.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'df5428e344b9b45b74ab356dc35fd0c1'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.009.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.009.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '019e4aa60457369dfa6074b392e9e108'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.010.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.010.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '76187cdd2f9b19750049210b3a3c8453'
'b.e21.BHISTsmbb.f09_g17.LE2-1011.001.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1011.001.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '113606e86401f009108c36db86627acf'
'b.e21.BHISTsmbb.f09_g17.LE2-1031.002.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1031.002.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '56ff0b651c9c9b0c1ff6b6dd12ccd204'
'b.e21.BHISTsmbb.f09_g17.LE2-1051.003.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1051.003.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f000c8fadeb21d4c34e93d0567494cf1'
'b.e21.BHISTsmbb.f09_g17.LE2-1071.004.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1071.004.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8f041ee5ce95e7d85f80bd1e93fed187'
'b.e21.BHISTsmbb.f09_g17.LE2-1091.005.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1091.005.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6b60f5d87a739cec2cab84f4faacda9e'
'b.e21.BHISTsmbb.f09_g17.LE2-1111.006.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1111.006.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ef966e22ab516981839a7a2dfa12de9d'
'b.e21.BHISTsmbb.f09_g17.LE2-1131.007.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1131.007.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '457f112fb6290c35953d84a51979a5cf'
'b.e21.BHISTsmbb.f09_g17.LE2-1151.008.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1151.008.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '572a5716be3be64b7e66fb85a07f587c'
'b.e21.BHISTsmbb.f09_g17.LE2-1171.009.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1171.009.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '161300958b6b4147047ab7161a89b255'
'b.e21.BHISTsmbb.f09_g17.LE2-1191.010.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1191.010.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd8abd0a2ceeca99ffec1d5ec7f6be2dd'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.011.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.011.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '23505849ea4aac35eb5ad2ca0f382fa8'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.012.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.012.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f9fdc5d24da6d5d4bb1e26ea942c87b7'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.013.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.013.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '294712e6fe9619b435466923981b3d34'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.014.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.014.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a11c554ef1cbe6f2bf0a4485ecd1cfa9'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.015.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.015.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b022a206e4db766bbb5c18c7cf6a0a15'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.016.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.016.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '480d7271e08a37ecb65c1285f6f8c353'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.017.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.017.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5f672d2a5609b3871b376e72ae2c1769'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.018.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.018.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '89dd899aa9e98e9e9702fb8905258fcd'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.019.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.019.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd54d45b0b004e39a8253ddb5d3783abd'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.020.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.020.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '407f4fb075a862c768ceb4d6af8f5598'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.011.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.011.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '25e16a47821ff60ca7b34755619d7194'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.012.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.012.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6c201f5ca8a4121ea817f809aa9ea7bd'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.013.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.013.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '76d99911e178222b71a8d04dc5530857'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.014.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.014.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3c709b60db1688f89c7f0b1b1c5a37e0'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.015.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.015.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd06d72e7c3a2a2194dd0ffc4bb124408'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.016.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.016.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0195d1c9f695e084e7080167627ecc33'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.017.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.017.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0c68aea4814318f0ab5a116be34699c1'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.018.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.018.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f3f1ac1f071ad9568330ea5cf4a24ccb'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.019.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.019.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '99028dc52bbd8aa1cca007dd1023a0c1'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.020.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.020.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '85a586605226bedfeed127cc0a73f2c4'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.011.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.011.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b718ac6c65004133614c3f97601ea5e0'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.012.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.012.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2cb91f6a5932ab0c5784c5ec2306ce84'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.013.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.013.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ea8ec7337372f00d13b7c08bdf4428ba'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.014.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.014.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c881d93ac8cff3c4815e12c7d942ebe4'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.015.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.015.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '36a247e2ef2e014553524b2b634f36c2'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.016.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.016.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '077bc74189a12b0498ef69a3c6ff037a'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.017.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.017.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2da8ab9eed77626ada113108cd3492ae'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.018.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.018.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '85048cbdd2851ee682bd0161f0c76b00'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.019.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.019.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7945465b48352d73351efa87ab5cd016'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.020.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.020.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c28c6dd7e22ab7b4637aa71258f1acc0'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.011.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.011.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'bd12a1ca7fa6024a479f39a2d6563711'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.012.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.012.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'eb45f9a8184313256b9c0362dadf3a06'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.013.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.013.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c4ab7c0f9f84eefe58ea4488b4ec24cb'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.014.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.014.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '28327b24f904b849548419edc0b22679'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.015.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.015.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '13d047559e0a4bf2275fd9a6c5a4c6ab'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.016.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.016.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '02fda598e5a10f5ae6b52986a4298d9b'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.017.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.017.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a45d3123aa15a3e6ff59130a3a777ec9'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.018.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.018.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1954c04ff6e5ef6f823d20bb13b61ecd'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.019.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.019.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '224cd2104c45e5f4bdd5a18b0b4f5f83'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.020.pop.h.diatChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diatChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.020.pop.h.diatChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd26df167a92e074f999d5314ccef5d6c'
EOF--dataset.file.url.chksum_type.chksum

}


#
# MAIN
#
echo "Running $(basename $0) version: $version"

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE

download

#remove duplicates (if any)
{ rm $CACHE_FILE && tac | awk '!x[$1]++' | tac > $CACHE_FILE; } < $CACHE_FILE

