#!/bin/bash


WGET_VERSION=$(wget --version | grep -oie "wget [0-9][0-9.]*" | head -n 1 | awk '{print $2}')
if [ -z "$WGET_VERSION" ]
then
WGET_VERSION=PARSE_ERROR
fi

WGET_USER_AGENT="wget/$WGET_VERSION/esg/4.3.2-20230405-191025/created/2023-04-11T07:47:18-06:00"


##############################################################################
#
# Climate Data Gateway download script
#
#
# Generated by: NCAR Climate Data Gateway
#
# Template version: 0.4.7-wget-checksum
#
#
# Your download selection includes data that might be secured using API Token based
# authentication. Therefore, this script can have your api-token. If you
# re-generate your API Token after you download this script, the download will
# fail. If that happens, you can either re-download this script or you can replace
# the old API Token with the new one by going to the Account Home:
#
# https://www.earthsystemgrid.org/account/user/account-home.html
#
# and clicking on "API Token" link under "Personal Account". You will be asked
# to log into the application before you can view your API Token.
#
#
# Dataset
# ucar.cgd.cesm2le.ocn.proc.monthly_ave.diazChl
# f415ad4a-1cd6-43e3-b01b-a130bde00a0a
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.ocn.proc.monthly_ave.diazChl.html
# https://www.earthsystemgrid.org/dataset/id/f415ad4a-1cd6-43e3-b01b-a130bde00a0a.html
#
# Dataset Version
# 1
# 67461dda-1169-4937-9217-410f6abb073f
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.ocn.proc.monthly_ave.diazChl/version/1.html
# https://www.earthsystemgrid.org/dataset/version/id/67461dda-1169-4937-9217-410f6abb073f.html
#
##############################################################################

CACHE_FILE=.md5_results
MAX_RETRY=3


usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
}
#defaults
debug=0
clean_work=1
verbose=1

#parse flags

while getopts ':pdvqko:' OPT; do

    case $OPT in

        p) clean_work=0;;       #    : preserve data that failed checksum
        o) output="$OPTARG";;   #<file>    : Write output for DML in the given file
        d) debug=1;;            #    : display debug information
        v) verbose=1;;          #       : be more verbose
        q) quiet=1;;            #    : be less verbose
        k) cert=1;;            #    : add --no-check-certificate
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

if [[ "$output" ]]; then
    #check and prepare the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    : > "$output" || { echo "Can't write file $output"; break; }
fi

    ((debug)) && echo "debug=$debug, cert=$cert, verbose=$verbose, quiet=$quiet, clean_work=$clean_work"

##############################################################################


check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum

    case $chk_type in
        md5) local_chksum=$(md5sum "$file" | cut -f1 -d" ");;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value"
    diff -q <(echo $local_chksum) <(echo $chk_value) >/dev/null
}

download() {

    if [[ "$cert" ]]; then
      wget="wget --no-check-certificate -c --user-agent=$WGET_USER_AGENT"
    else
      wget="wget -c --user-agent=$WGET_USER_AGENT"
    fi

    ((quiet)) && wget="$wget -q" || { ((!verbose)) && wget="$wget -nv"; }

    ((debug)) && echo "wget command: $wget"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #are we just writing a file?
        if [ "$output" ]; then
            echo "$file - $url" >> $output
            echo ""
            continue
        fi

        retry_counter=0

        while : ; do
                #if we have the file, check if it's already processed.
                [ -f "$file" ] && cached="$(grep $file $CACHE_FILE)" || unset cached

                #check it wasn't modified
                if [[ -n "$cached" && "$(stat -c %Y $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    echo "Already downloaded and verified"
                    break
                fi

                # (if we had the file size, we could check before trying to complete)
                echo "Downloading"
                $wget -O "$file" $url || { failed=1; break; }

                #check if file is there
                if [[ -f "$file" ]]; then
                        ((debug)) && echo file found
                        if ! check_chksum "$file" $chksum_type $chksum; then
                                echo "  $chksum_type failed!"
                                if ((clean_work)); then
                                        rm "$file"

                                        #try again up to n times
                                        echo -n "  Re-downloading..."

                                        if [ $retry_counter -eq $MAX_RETRY]
                                        then
                                            echo "  Re-tried file $file $MAX_RETRY times...."
                                            break
                                        fi
                                        retry_counter=`expr $retry_counter + 1`

                                        continue
                                else
                                        echo "  don't use -p or remove manually."
                                fi
                        else
                                echo "  $chksum_type ok. done!"
                                echo "$file" $(stat -c %Y "$file") $chksum >> $CACHE_FILE
                        fi
                fi
                #done!
                break
        done

        if ((failed)); then
            echo "download failed"

            unset failed
        fi

    done <<EOF--dataset.file.url.chksum_type.chksum
'b.e21.BHISTcmip6.f09_g17.LE2-1001.001.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1001.001.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '55fb6685ef713ba310de5affe69a8ff2'
'b.e21.BHISTcmip6.f09_g17.LE2-1021.002.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1021.002.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a25cb8e4a92d4f67d1700101237689c9'
'b.e21.BHISTcmip6.f09_g17.LE2-1041.003.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1041.003.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '03afffd78e2ff9b70c6607726aff8f5a'
'b.e21.BHISTcmip6.f09_g17.LE2-1061.004.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1061.004.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5e80a4ed1e2850eb62055318c6759204'
'b.e21.BHISTcmip6.f09_g17.LE2-1081.005.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1081.005.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4fc01e1d49818f9729c5121da2f99ee0'
'b.e21.BHISTcmip6.f09_g17.LE2-1101.006.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1101.006.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7920995980a500642a11a70471a81de1'
'b.e21.BHISTcmip6.f09_g17.LE2-1121.007.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1121.007.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8387c04a435c9500a79a825ff0a7cda2'
'b.e21.BHISTcmip6.f09_g17.LE2-1141.008.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1141.008.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '352331cb1757bbbfd58ac67477739f5c'
'b.e21.BHISTcmip6.f09_g17.LE2-1161.009.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1161.009.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a6dd4fbc276723c65356c5dcaafc8a74'
'b.e21.BHISTcmip6.f09_g17.LE2-1181.010.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1181.010.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5431d102ca085317043aad236c7141f9'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.001.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.001.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '34489a573fbd1fdc3ef899b2848f40f3'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.002.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.002.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a7628bf7ab8e1c15d0451cc9ab412c19'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.003.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.003.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '61e588df8bc242e0c44cd14373b088f8'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.004.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.004.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3f13becdaa419ea3ff3c9bfb4259fc6b'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.005.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.005.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1eab086b614e16a1f85e3c8661901587'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.006.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.006.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'fcd1a46dddce0c2265c8a157897d120a'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.007.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.007.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5c11fc95289832b8eb64f31bb1043f1e'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.008.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.008.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'be7ebcd7240b98f2aaba592eb4530d7c'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.009.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.009.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b1c1262cc0211f070c856984e552131e'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.010.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.010.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '14a24b76bb51838828963bc199102534'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.001.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.001.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd5aa987d450341057694ae92cebf65bf'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.002.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.002.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd015548b5bbfedf5593f2dddff79da4d'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.003.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.003.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c838a9476d31b321771268bb1a636d40'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.004.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.004.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3442fb791d6dfb59fad35430e4979b10'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.005.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.005.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1a1a10666eb994edd9afe2d285e68c95'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.006.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.006.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '09ec3eab6295a83e2cf8ad624b6aa92d'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.007.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.007.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5a8e26ec4288ec48f6ee1a782ccdf111'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.008.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.008.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '46878deb620a422972289776219af7c8'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.009.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.009.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'efaba0c660b1f427b555400856b87952'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.010.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.010.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7f8d5da6b8e6ca24526830216e8ffb1d'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.001.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.001.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '73b40dab0cbcb59b1a419b601ee8401e'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.002.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.002.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e65b808fed7805cb3ad639b2197aaff9'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.003.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.003.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd15806b67438acb34ab5f2aa34e50b17'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.004.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.004.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c040361538d39f6aa13e0a13f7750ee3'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.005.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.005.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '96b0b72462aa1e038fb4c1caaa0aab7e'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.006.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.006.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0d78d983ef7ccb6c572a7bb06e10547f'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.007.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.007.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b67d38296232cdad8cc18ab8d707820e'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.008.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.008.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '907d0be07522363c190bef3ea2ac9bbf'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.009.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.009.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'aaaf45915b9628695a375ccf6f73c395'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.010.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.010.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cad2585007c76b36246b1d78f6c477b4'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.001.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.001.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '89759330b5cf6db1c954b4f551cda0a1'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.002.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.002.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8281e61bf69c412dcf94896f7ccaccfc'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.003.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.003.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a8b65aee2fbb7123956e4a65bec26801'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.004.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.004.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5cb4bf4a96c16bc5df0b75e34b8a48b0'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.005.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.005.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '19b5667837371a06da8b4f5a2a6175c2'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.006.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.006.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e842eac98cb7b6a35fe88ccb957807a3'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.007.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.007.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8fcc23227d53286a46ccbb285729daa7'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.008.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.008.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '002ab9034493c6033be0dc82f2321330'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.009.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.009.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '32274e28c21c481a5f66cd798f66017b'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.010.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.010.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '737b704515bddc27795a0ffdeb6236c0'
'b.e21.BHISTsmbb.f09_g17.LE2-1011.001.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1011.001.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b1df5723e4580bfe756e5d3687edd2bc'
'b.e21.BHISTsmbb.f09_g17.LE2-1031.002.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1031.002.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7926083a34b911f9ac4770e850c6dfcd'
'b.e21.BHISTsmbb.f09_g17.LE2-1051.003.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1051.003.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'dfd8f8c4717ae91459cb1b90a5a4548f'
'b.e21.BHISTsmbb.f09_g17.LE2-1071.004.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1071.004.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8b0ab9b70c26f4a908e8cbfdd8687495'
'b.e21.BHISTsmbb.f09_g17.LE2-1091.005.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1091.005.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8f9288c4a461786440731e869c9e0e1b'
'b.e21.BHISTsmbb.f09_g17.LE2-1111.006.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1111.006.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f1ba42173027723f1333f5472c205745'
'b.e21.BHISTsmbb.f09_g17.LE2-1131.007.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1131.007.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c46168603e7494fc523314e55d9ee8c3'
'b.e21.BHISTsmbb.f09_g17.LE2-1151.008.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1151.008.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '53981c737d7ab9547af3dbaf899a75a5'
'b.e21.BHISTsmbb.f09_g17.LE2-1171.009.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1171.009.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '31a3a8d32421f1aab00de373a6dd2f5d'
'b.e21.BHISTsmbb.f09_g17.LE2-1191.010.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1191.010.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'fc0cbfcf08ad619ae3210c000a89fd16'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.011.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.011.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '18dfb483751f8cad8efb5ee87c08bde4'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.012.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.012.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'dcc965bca0a2f1e84068726a50e0aa6b'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.013.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.013.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e75bdafe7c5221dddce66bece7b99be7'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.014.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.014.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'dc5b6fa1d1eae9a6615d7c87f9e22176'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.015.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.015.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f236076c6dc496d6f61871c15a49acae'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.016.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.016.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd803bb59631fb442e8ad2669953fe17e'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.017.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.017.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'abd5a5fde0e44ad1bfcbdbce70ddebc6'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.018.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.018.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0c718fdc283e493c22dfdbe0e89e21a8'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.019.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.019.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ea107be1c86a77d885136c56be7b38f9'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.020.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.020.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '85a850c38826014e7517ede4db823c88'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.011.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.011.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5f4b683411e377b9f04201c34c3c7838'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.012.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.012.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd40b2da54708776ab065ffc1e22d1d6b'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.013.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.013.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8d9c6df128ee4759a633264697a75d03'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.014.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.014.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a4f1003105f7f9466ef9ff64b7a79666'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.015.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.015.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'fc0c02bfa42c56710703d1498a61b827'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.016.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.016.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'fcf28c53ba14cad800be254fc78a6982'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.017.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.017.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'bd848faba51f4e018c5a1078c3b5a8f6'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.018.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.018.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8a70ca6d2fe60f8290148c6947113dcd'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.019.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.019.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'be84fd101dd44621f0e39c2779ce42c5'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.020.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.020.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ddb1efd92cd5082437df8a724f664357'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.011.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.011.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '39aeb799f863873bf2049771e07a1137'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.012.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.012.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a43c24aef1030e89ce3ef1c62a8302fd'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.013.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.013.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '715ed063c07ebde12ebe0df166878e14'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.014.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.014.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9fa6b9045c485c1ccbd358d5516ef6f2'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.015.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.015.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b6058e2868e5670845cc5aeff82a1778'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.016.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.016.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'df47d2c801f78fcaacde1e19f534031f'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.017.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.017.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ebbc40be61f522fd3810f7f92dabad10'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.018.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.018.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4a833cb0776c6bf9a48dab0f457fbfa0'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.019.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.019.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a6b768048b900d775fde8aec2386abdd'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.020.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.020.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8228f0ecfd5a7d2b64490637c992d84e'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.011.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.011.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '48de1a67032c778a03b13f85009bb0b9'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.012.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.012.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5da57bff4bf7632c63a265fc2aeea802'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.013.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.013.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '154e4e06a263bb8e0bc3dda6783cfe4d'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.014.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.014.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd9cc06e9cab33b028c9bcd17bdabf028'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.015.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.015.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd0b07f2c186eecab0f8945027cd70b6c'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.016.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.016.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ee9c78d18625ccb387bc97ee02a99f4e'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.017.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.017.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f0c63e7825ca77d4f6ba3837a0130eb7'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.018.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.018.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0e4ae0629dcd98d61e37f8e8ed084ff5'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.019.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.019.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0fac4a23af971d15ddba5b010bf818c9'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.020.pop.h.diazChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.020.pop.h.diazChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3a5e80ac168e09265b44920e6e4707cd'
EOF--dataset.file.url.chksum_type.chksum

}


#
# MAIN
#
echo "Running $(basename $0) version: $version"

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE

download

#remove duplicates (if any)
{ rm $CACHE_FILE && tac | awk '!x[$1]++' | tac > $CACHE_FILE; } < $CACHE_FILE

