#!/bin/bash


WGET_VERSION=$(wget --version | grep -oie "wget [0-9][0-9.]*" | head -n 1 | awk '{print $2}')
if [ -z "$WGET_VERSION" ]
then
WGET_VERSION=PARSE_ERROR
fi

WGET_USER_AGENT="wget/$WGET_VERSION/esg/4.3.2-20230405-191025/created/2023-04-11T07:47:04-06:00"


##############################################################################
#
# Climate Data Gateway download script
#
#
# Generated by: NCAR Climate Data Gateway
#
# Template version: 0.4.7-wget-checksum
#
#
# Your download selection includes data that might be secured using API Token based
# authentication. Therefore, this script can have your api-token. If you
# re-generate your API Token after you download this script, the download will
# fail. If that happens, you can either re-download this script or you can replace
# the old API Token with the new one by going to the Account Home:
#
# https://www.earthsystemgrid.org/account/user/account-home.html
#
# and clicking on "API Token" link under "Personal Account". You will be asked
# to log into the application before you can view your API Token.
#
#
# Dataset
# ucar.cgd.cesm2le.ocn.proc.monthly_ave.diazChl
# f415ad4a-1cd6-43e3-b01b-a130bde00a0a
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.ocn.proc.monthly_ave.diazChl.html
# https://www.earthsystemgrid.org/dataset/id/f415ad4a-1cd6-43e3-b01b-a130bde00a0a.html
#
# Dataset Version
# 1
# 67461dda-1169-4937-9217-410f6abb073f
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.ocn.proc.monthly_ave.diazChl/version/1.html
# https://www.earthsystemgrid.org/dataset/version/id/67461dda-1169-4937-9217-410f6abb073f.html
#
##############################################################################

CACHE_FILE=.md5_results
MAX_RETRY=3


usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
}
#defaults
debug=0
clean_work=1
verbose=1

#parse flags

while getopts ':pdvqko:' OPT; do

    case $OPT in

        p) clean_work=0;;       #    : preserve data that failed checksum
        o) output="$OPTARG";;   #<file>    : Write output for DML in the given file
        d) debug=1;;            #    : display debug information
        v) verbose=1;;          #       : be more verbose
        q) quiet=1;;            #    : be less verbose
        k) cert=1;;            #    : add --no-check-certificate
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

if [[ "$output" ]]; then
    #check and prepare the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    : > "$output" || { echo "Can't write file $output"; break; }
fi

    ((debug)) && echo "debug=$debug, cert=$cert, verbose=$verbose, quiet=$quiet, clean_work=$clean_work"

##############################################################################


check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum

    case $chk_type in
        md5) local_chksum=$(md5sum "$file" | cut -f1 -d" ");;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value"
    diff -q <(echo $local_chksum) <(echo $chk_value) >/dev/null
}

download() {

    if [[ "$cert" ]]; then
      wget="wget --no-check-certificate -c --user-agent=$WGET_USER_AGENT"
    else
      wget="wget -c --user-agent=$WGET_USER_AGENT"
    fi

    ((quiet)) && wget="$wget -q" || { ((!verbose)) && wget="$wget -nv"; }

    ((debug)) && echo "wget command: $wget"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #are we just writing a file?
        if [ "$output" ]; then
            echo "$file - $url" >> $output
            echo ""
            continue
        fi

        retry_counter=0

        while : ; do
                #if we have the file, check if it's already processed.
                [ -f "$file" ] && cached="$(grep $file $CACHE_FILE)" || unset cached

                #check it wasn't modified
                if [[ -n "$cached" && "$(stat -c %Y $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    echo "Already downloaded and verified"
                    break
                fi

                # (if we had the file size, we could check before trying to complete)
                echo "Downloading"
                $wget -O "$file" $url || { failed=1; break; }

                #check if file is there
                if [[ -f "$file" ]]; then
                        ((debug)) && echo file found
                        if ! check_chksum "$file" $chksum_type $chksum; then
                                echo "  $chksum_type failed!"
                                if ((clean_work)); then
                                        rm "$file"

                                        #try again up to n times
                                        echo -n "  Re-downloading..."

                                        if [ $retry_counter -eq $MAX_RETRY]
                                        then
                                            echo "  Re-tried file $file $MAX_RETRY times...."
                                            break
                                        fi
                                        retry_counter=`expr $retry_counter + 1`

                                        continue
                                else
                                        echo "  don't use -p or remove manually."
                                fi
                        else
                                echo "  $chksum_type ok. done!"
                                echo "$file" $(stat -c %Y "$file") $chksum >> $CACHE_FILE
                        fi
                fi
                #done!
                break
        done

        if ((failed)); then
            echo "download failed"

            unset failed
        fi

    done <<EOF--dataset.file.url.chksum_type.chksum
'b.e21.BHISTcmip6.f09_g17.LE2-1001.001.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1001.001.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '07ac18da9bb2dd8fc2eb57b09ca30a4c'
'b.e21.BHISTcmip6.f09_g17.LE2-1021.002.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1021.002.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'eccac10253ef79d1a6706f6d31a0e188'
'b.e21.BHISTcmip6.f09_g17.LE2-1041.003.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1041.003.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1e11087c83bc4a27e83f73378221dc6a'
'b.e21.BHISTcmip6.f09_g17.LE2-1061.004.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1061.004.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7596d5e5ab59e544918263ae09ab5616'
'b.e21.BHISTcmip6.f09_g17.LE2-1081.005.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1081.005.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0fe3538591c7d891a3af2ff37ed37c17'
'b.e21.BHISTcmip6.f09_g17.LE2-1101.006.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1101.006.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'af9494ac39102ea17f52a00c411ba79a'
'b.e21.BHISTcmip6.f09_g17.LE2-1121.007.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1121.007.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'be4b9f29be1885d27ad2171e73fb0633'
'b.e21.BHISTcmip6.f09_g17.LE2-1141.008.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1141.008.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cf9535e615af2177ebd1ec282b6f4f74'
'b.e21.BHISTcmip6.f09_g17.LE2-1161.009.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1161.009.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '78be945b83f72b7e78686ac144e3a85e'
'b.e21.BHISTcmip6.f09_g17.LE2-1181.010.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1181.010.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'aa82f423cb501a22fdca2f9e8a143d09'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.001.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.001.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4962e677676561b79a06b34d62b4b5cf'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.002.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.002.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a7f2e110bfda16c485d88bd364bdade1'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.003.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.003.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6cadfbe1f2656052f69d6f1794324202'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.004.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.004.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '36523678bfcb9f41dfd1be71aff02a78'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.005.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.005.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '324c6377f3ca96bf0ba3ddcb458d54c1'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.006.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.006.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '81847dc33f8ff5f955e6e1fc501c2fc3'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.007.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.007.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cc61ea340f2c53754f4c1c0ec802fd26'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.008.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.008.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5dce5fbd6775f7387663e8c6735a7d7b'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.009.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.009.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6e1364d526d1c397c4f2b4aa466f5db4'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.010.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.010.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'eeaac3b54066bea6b470b585f2927812'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.001.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.001.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6137c4ecb16cfcb4dc30af9f4d35a273'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.002.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.002.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '66d06e851a5f5fd0ac5340a61b23625f'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.003.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.003.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e951e56fb88bd22d65716c6a45ce32cc'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.004.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.004.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'acf89887a2bb4218b9a47a2dc2420c91'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.005.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.005.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '94e0e8545f96e7fe1dca2e13773e718a'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.006.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.006.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ac55ea9ac22c4792b10a67c7d4ba0891'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.007.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.007.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2ad6abcab9403628160f9524cb72c559'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.008.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.008.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '72e580c1f4f4ad5ae9f62769f76e7a5f'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.009.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.009.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '42530e06d406e8b205cac6dce46ec474'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.010.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.010.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cc4d89c9abfbebc7582ddfc09ef0d71d'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.001.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.001.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a77611c9800c9016e425e769902d2de4'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.002.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.002.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '23f616605d3584b175a3898930607a36'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.003.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.003.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '14a65c90e3c14b22699c9dffc0568d17'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.004.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.004.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9554876dcce9b092ddd3d2657f59aa76'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.005.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.005.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ce39c5d5cd8ae954ee4d65115dfef8ca'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.006.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.006.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4e5c10ce5416881457e6b2435c5a4cd9'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.007.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.007.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ee6d2d3f6f2f7ef0351362fd16adc423'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.008.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.008.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '52e1049129c3867d797cacd646e88e5b'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.009.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.009.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9bbfa3758ffd4b67f33744e8e27f2e47'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.010.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.010.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'fd1fe3216ddb69c56a11262669820b71'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.001.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.001.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'db61c5d615f503efdab1b1dab861d3ea'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.002.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.002.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'bc9d56af6c0f59133bcdf83fa3702a95'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.003.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.003.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '23aed95df2717e587cb9e8b96fb97aad'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.004.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.004.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7bca8ed391a7d9efd6655c61f9481e86'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.005.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.005.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b1d7835203b0d8f9cb583d8c51bde673'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.006.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.006.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '96c059b249ba096fa59483a5a6d8fe34'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.007.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.007.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5a2cd384f5c77f9fd634093f25501614'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.008.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.008.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c2afc6139396775571bbb4f5a077b940'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.009.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.009.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '000da5eedf1e44325dd1e392d3abdfa4'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.010.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.010.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ebe23cb4a428aff7502c180877ab07e9'
'b.e21.BHISTsmbb.f09_g17.LE2-1011.001.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1011.001.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6f6d122a85b1aa45b46df5516fc64af0'
'b.e21.BHISTsmbb.f09_g17.LE2-1031.002.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1031.002.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '64d9ce06b15f9b07c0df54ee8b04bd87'
'b.e21.BHISTsmbb.f09_g17.LE2-1051.003.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1051.003.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c0cd71cf44b5f30045c0a650c3bb6728'
'b.e21.BHISTsmbb.f09_g17.LE2-1071.004.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1071.004.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '58096e92db46d743e079bf1889cc3afe'
'b.e21.BHISTsmbb.f09_g17.LE2-1091.005.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1091.005.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cb6b62b1d800eda9fbd5887db865d9f7'
'b.e21.BHISTsmbb.f09_g17.LE2-1111.006.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1111.006.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '556da0057a546c36a4dd97aa9ac7cd58'
'b.e21.BHISTsmbb.f09_g17.LE2-1131.007.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1131.007.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '21b7b1fdf715093a6f3e5f0795c7b6cb'
'b.e21.BHISTsmbb.f09_g17.LE2-1151.008.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1151.008.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '67e5bec43ab5472c4108a72f91dfe31d'
'b.e21.BHISTsmbb.f09_g17.LE2-1171.009.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1171.009.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7912eb306e1ffee6367ac93f32dbc432'
'b.e21.BHISTsmbb.f09_g17.LE2-1191.010.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1191.010.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c973762dd7e0aafe917157c4d6ac41e6'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.011.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.011.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a27488d4ac1917952d3d4c350a1c7c03'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.012.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.012.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6a4ca43a65cbb9199ec7ea2cdff7635d'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.013.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.013.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1beff0f3ce20ac99c3f079df89817b49'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.014.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.014.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3da43a7e49bac90ec01182099a8d4fd2'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.015.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.015.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3fbfdd6339dd43f01343eb4ab0c8c195'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.016.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.016.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '538611894c877a6a45eff45cbe006777'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.017.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.017.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4d1165237c27d9ff6a401b7be38c02bb'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.018.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.018.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'da89d89d20337ed6166603484a8191b7'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.019.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.019.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6cc1f10f71d9a93a67939807a964f8d3'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.020.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.020.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f62a02dc3d13072a10d8a1e90e7b39e0'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.011.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.011.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'df58bf5676cbcc5a7a0fe384de246a89'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.012.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.012.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0e812db65ecaf66000fc0393aabfcd4a'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.013.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.013.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '917b464b24382e1f6972731e2e3085a3'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.014.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.014.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ccef8840d2a4e65a232a108ad8155987'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.015.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.015.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '18a44875c0a5713999fe443edfcf55cc'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.016.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.016.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'be0d740153a2b58ec624b5aa60672d75'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.017.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.017.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '97c62e6544a0cd2d2658384baffa0ee9'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.018.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.018.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5aec21d9b3a17751a911fba6bd2c39b6'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.019.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.019.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '32daa693b49b8a72d987f44e7bc47e89'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.020.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.020.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c85a9d0bda33ac8ca9f5ebe792ed21bf'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.011.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.011.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4b86db8e6b3baf05d759ee6324ba6297'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.012.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.012.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '78bd8e44d664406c1308191d94a8a05c'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.013.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.013.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'bc06bdb668cc0f02b1bad422a94b50a2'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.014.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.014.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ceb9566ef6a67f3188ff3622a0d1bf7c'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.015.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.015.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '08a6e4f6aaa81695076ace68dd4cadb5'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.016.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.016.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '52bcbbf83eb472a9f609e31ef71636fd'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.017.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.017.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e6e81ce9f0689c90f1c7126159f0fbcd'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.018.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.018.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd3c5def0cbe56eef1d6c14edbecb49a7'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.019.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.019.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3078e5503456007ad452a684df8e2396'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.020.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.020.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4b9d3bdf2917e24ef163631632eb6f6b'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.011.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.011.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '68eb1db8748c69ed97c25e7d4f4df7b8'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.012.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.012.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '82a596ad17e2d0292226ecca590f4896'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.013.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.013.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ed65e1a7311fdef134010322f74078f6'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.014.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.014.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cf0c93251996d7edfe3106b7751c9a12'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.015.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.015.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'fb31ecee49419611641adcca656928bb'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.016.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.016.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7a6985478ee054f71544b459c17d4901'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.017.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.017.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '14b4d35077535a27854933d11fd99542'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.018.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.018.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'da4975ac9ec74dcd3dadf19c38b54a85'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.019.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.019.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f25f1082d37d8daec6348a254e82bbb5'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.020.pop.h.diazChl.199001-199912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/diazChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.020.pop.h.diazChl.199001-199912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'de630dd598798eff70afdc52e823af2c'
EOF--dataset.file.url.chksum_type.chksum

}


#
# MAIN
#
echo "Running $(basename $0) version: $version"

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE

download

#remove duplicates (if any)
{ rm $CACHE_FILE && tac | awk '!x[$1]++' | tac > $CACHE_FILE; } < $CACHE_FILE

