#!/bin/bash


WGET_VERSION=$(wget --version | grep -oie "wget [0-9][0-9.]*" | head -n 1 | awk '{print $2}')
if [ -z "$WGET_VERSION" ]
then
WGET_VERSION=PARSE_ERROR
fi

WGET_USER_AGENT="wget/$WGET_VERSION/esg/4.3.2-20230405-191025/created/2023-04-11T07:49:50-06:00"


##############################################################################
#
# Climate Data Gateway download script
#
#
# Generated by: NCAR Climate Data Gateway
#
# Template version: 0.4.7-wget-checksum
#
#
# Your download selection includes data that might be secured using API Token based
# authentication. Therefore, this script can have your api-token. If you
# re-generate your API Token after you download this script, the download will
# fail. If that happens, you can either re-download this script or you can replace
# the old API Token with the new one by going to the Account Home:
#
# https://www.earthsystemgrid.org/account/user/account-home.html
#
# and clicking on "API Token" link under "Personal Account". You will be asked
# to log into the application before you can view your API Token.
#
#
# Dataset
# ucar.cgd.cesm2le.ocn.proc.monthly_ave.spChl
# acc57864-9900-4fb7-a0a0-564dcdd927f4
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.ocn.proc.monthly_ave.spChl.html
# https://www.earthsystemgrid.org/dataset/id/acc57864-9900-4fb7-a0a0-564dcdd927f4.html
#
# Dataset Version
# 2
# c8d7e215-c5e7-4286-8390-617d81c3cc60
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.ocn.proc.monthly_ave.spChl/version/2.html
# https://www.earthsystemgrid.org/dataset/version/id/c8d7e215-c5e7-4286-8390-617d81c3cc60.html
#
##############################################################################

CACHE_FILE=.md5_results
MAX_RETRY=3


usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
}
#defaults
debug=0
clean_work=1
verbose=1

#parse flags

while getopts ':pdvqko:' OPT; do

    case $OPT in

        p) clean_work=0;;       #    : preserve data that failed checksum
        o) output="$OPTARG";;   #<file>    : Write output for DML in the given file
        d) debug=1;;            #    : display debug information
        v) verbose=1;;          #       : be more verbose
        q) quiet=1;;            #    : be less verbose
        k) cert=1;;            #    : add --no-check-certificate
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

if [[ "$output" ]]; then
    #check and prepare the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    : > "$output" || { echo "Can't write file $output"; break; }
fi

    ((debug)) && echo "debug=$debug, cert=$cert, verbose=$verbose, quiet=$quiet, clean_work=$clean_work"

##############################################################################


check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum

    case $chk_type in
        md5) local_chksum=$(md5sum "$file" | cut -f1 -d" ");;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value"
    diff -q <(echo $local_chksum) <(echo $chk_value) >/dev/null
}

download() {

    if [[ "$cert" ]]; then
      wget="wget --no-check-certificate -c --user-agent=$WGET_USER_AGENT"
    else
      wget="wget -c --user-agent=$WGET_USER_AGENT"
    fi

    ((quiet)) && wget="$wget -q" || { ((!verbose)) && wget="$wget -nv"; }

    ((debug)) && echo "wget command: $wget"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #are we just writing a file?
        if [ "$output" ]; then
            echo "$file - $url" >> $output
            echo ""
            continue
        fi

        retry_counter=0

        while : ; do
                #if we have the file, check if it's already processed.
                [ -f "$file" ] && cached="$(grep $file $CACHE_FILE)" || unset cached

                #check it wasn't modified
                if [[ -n "$cached" && "$(stat -c %Y $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    echo "Already downloaded and verified"
                    break
                fi

                # (if we had the file size, we could check before trying to complete)
                echo "Downloading"
                $wget -O "$file" $url || { failed=1; break; }

                #check if file is there
                if [[ -f "$file" ]]; then
                        ((debug)) && echo file found
                        if ! check_chksum "$file" $chksum_type $chksum; then
                                echo "  $chksum_type failed!"
                                if ((clean_work)); then
                                        rm "$file"

                                        #try again up to n times
                                        echo -n "  Re-downloading..."

                                        if [ $retry_counter -eq $MAX_RETRY]
                                        then
                                            echo "  Re-tried file $file $MAX_RETRY times...."
                                            break
                                        fi
                                        retry_counter=`expr $retry_counter + 1`

                                        continue
                                else
                                        echo "  don't use -p or remove manually."
                                fi
                        else
                                echo "  $chksum_type ok. done!"
                                echo "$file" $(stat -c %Y "$file") $chksum >> $CACHE_FILE
                        fi
                fi
                #done!
                break
        done

        if ((failed)); then
            echo "download failed"

            unset failed
        fi

    done <<EOF--dataset.file.url.chksum_type.chksum
'b.e21.BSSP370cmip6.f09_g17.LE2-1001.001.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1001.001.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9eb0d5c3cc3f43874390d85dc3f33463'
'b.e21.BSSP370cmip6.f09_g17.LE2-1021.002.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1021.002.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '34303f52f395dff57fcc019b9dd724ce'
'b.e21.BSSP370cmip6.f09_g17.LE2-1041.003.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1041.003.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4a50dee139dec7a05f40954613d1251e'
'b.e21.BSSP370cmip6.f09_g17.LE2-1061.004.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1061.004.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '61141a5f36ac6bbb7cce6c615da764a4'
'b.e21.BSSP370cmip6.f09_g17.LE2-1081.005.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1081.005.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e1fba92bbbab1d1b3f6a1df8d4d5f083'
'b.e21.BSSP370cmip6.f09_g17.LE2-1101.006.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1101.006.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '58dcf1ce4c8196e6d014e678d8af43a7'
'b.e21.BSSP370cmip6.f09_g17.LE2-1121.007.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1121.007.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c695d58aaf73ac7b57a133bb9cbc4718'
'b.e21.BSSP370cmip6.f09_g17.LE2-1141.008.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1141.008.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd75239f5d51c3ea8aa2cb19a5f739ca4'
'b.e21.BSSP370cmip6.f09_g17.LE2-1161.009.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1161.009.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '43b120b40665aef0318bc18d000b5f62'
'b.e21.BSSP370cmip6.f09_g17.LE2-1181.010.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1181.010.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '50aacb14627413f4291f880f1d5f307a'
'b.e21.BSSP370cmip6.f09_g17.LE2-1231.001.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1231.001.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0bf5fc3d0388aa1a93e78a8e2cdf0b86'
'b.e21.BSSP370cmip6.f09_g17.LE2-1231.002.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1231.002.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '337a3dd97b102343321ee49cc948c849'
'b.e21.BSSP370cmip6.f09_g17.LE2-1231.003.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1231.003.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '08ddfe057cc5512c4179d0732f841db0'
'b.e21.BSSP370cmip6.f09_g17.LE2-1231.004.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1231.004.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b56580597676ed297f75592335e139aa'
'b.e21.BSSP370cmip6.f09_g17.LE2-1231.005.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1231.005.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '161b2b8957e99c026e747e45b7a1c7b8'
'b.e21.BSSP370cmip6.f09_g17.LE2-1231.006.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1231.006.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2097b1f010666f5164a44572ed1fc3aa'
'b.e21.BSSP370cmip6.f09_g17.LE2-1231.007.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1231.007.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1914bbc3856937078d3cd56fa9251ec4'
'b.e21.BSSP370cmip6.f09_g17.LE2-1231.008.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1231.008.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3da1ad348c5ca73a9d56034c09287a43'
'b.e21.BSSP370cmip6.f09_g17.LE2-1231.009.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1231.009.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '61d505cad5d62bc23635fcca9244d45d'
'b.e21.BSSP370cmip6.f09_g17.LE2-1231.010.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1231.010.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2bef469ccb07899122da7859aa659a84'
'b.e21.BSSP370cmip6.f09_g17.LE2-1251.001.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1251.001.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b831a3bbbd4e26967fd572c8ddc6af7b'
'b.e21.BSSP370cmip6.f09_g17.LE2-1251.002.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1251.002.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1c0f9224c38aa2077e9a1cbe8c724b48'
'b.e21.BSSP370cmip6.f09_g17.LE2-1251.003.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1251.003.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd1c3857f0ad34e1e62eb9bbea2729355'
'b.e21.BSSP370cmip6.f09_g17.LE2-1251.004.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1251.004.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b957a2bc7feccc93d88e4f7114e7334e'
'b.e21.BSSP370cmip6.f09_g17.LE2-1251.005.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1251.005.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6391f1bad695c7a781c32a8d066aaf7d'
'b.e21.BSSP370cmip6.f09_g17.LE2-1251.006.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1251.006.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '07dc4749f40d84593ace88cc249759e7'
'b.e21.BSSP370cmip6.f09_g17.LE2-1251.007.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1251.007.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a68db5f02092ec0b492da0cf89203f3f'
'b.e21.BSSP370cmip6.f09_g17.LE2-1251.008.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1251.008.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5d64cf59c6128cb18507a3770771d433'
'b.e21.BSSP370cmip6.f09_g17.LE2-1251.009.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1251.009.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '16da108e770abafc5874fa2c54fe8202'
'b.e21.BSSP370cmip6.f09_g17.LE2-1251.010.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1251.010.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e94c0235fe995e75cad4e51e660afffd'
'b.e21.BSSP370cmip6.f09_g17.LE2-1281.001.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1281.001.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'fc509b3afcab089d299c503d881c2182'
'b.e21.BSSP370cmip6.f09_g17.LE2-1281.002.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1281.002.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f070c3ec88750e91c3ad543c15337473'
'b.e21.BSSP370cmip6.f09_g17.LE2-1281.003.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1281.003.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '58cd04ce92e88f26879ab3a56d78b23d'
'b.e21.BSSP370cmip6.f09_g17.LE2-1281.004.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1281.004.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'af235d9f2f0f8de09e0207f21500b242'
'b.e21.BSSP370cmip6.f09_g17.LE2-1281.005.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1281.005.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c5f4f565b020dd0951aacf09914373ce'
'b.e21.BSSP370cmip6.f09_g17.LE2-1281.006.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1281.006.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9467ed60aa660001802790d2fa923df8'
'b.e21.BSSP370cmip6.f09_g17.LE2-1281.007.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1281.007.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '925eeea917784cfb2f1982b35f3b9a98'
'b.e21.BSSP370cmip6.f09_g17.LE2-1281.008.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1281.008.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0b672b5b988f6b6aac1043a7e06213da'
'b.e21.BSSP370cmip6.f09_g17.LE2-1281.009.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1281.009.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f3c2f8485d0357cedae59084364144e5'
'b.e21.BSSP370cmip6.f09_g17.LE2-1281.010.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1281.010.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ccf081b3758da55f0cbc63ea05054f1a'
'b.e21.BSSP370cmip6.f09_g17.LE2-1301.001.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1301.001.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ebe549967dc42ad0d99504ffddda7fb7'
'b.e21.BSSP370cmip6.f09_g17.LE2-1301.002.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1301.002.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cbf6b26769d4c379da85b1da86f31752'
'b.e21.BSSP370cmip6.f09_g17.LE2-1301.003.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1301.003.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8ff8e788b001f2f82bb8da06c61a001a'
'b.e21.BSSP370cmip6.f09_g17.LE2-1301.004.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1301.004.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5c28bd591c0bce26230c1358ed16927e'
'b.e21.BSSP370cmip6.f09_g17.LE2-1301.005.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1301.005.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cfcdc3bfc327be9302b4b117a58239c7'
'b.e21.BSSP370cmip6.f09_g17.LE2-1301.006.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1301.006.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '38be5ec8437275b8136206dea2564e86'
'b.e21.BSSP370cmip6.f09_g17.LE2-1301.007.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1301.007.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ccf82ccd885463b3d1143465527f9371'
'b.e21.BSSP370cmip6.f09_g17.LE2-1301.008.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1301.008.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '51c9c865da2a96e4bd2d09ec5717a922'
'b.e21.BSSP370cmip6.f09_g17.LE2-1301.009.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1301.009.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '997e9b80eb778c975af777585df7710b'
'b.e21.BSSP370cmip6.f09_g17.LE2-1301.010.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370cmip6.f09_g17.LE2-1301.010.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0ad4e139ccd21d0ec7d04034ad2f3a6f'
'b.e21.BSSP370smbb.f09_g17.LE2-1011.001.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1011.001.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '29b5506967135dc8795791b23fea669d'
'b.e21.BSSP370smbb.f09_g17.LE2-1031.002.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1031.002.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8ff18f276e094f55a75c94fe7b811225'
'b.e21.BSSP370smbb.f09_g17.LE2-1051.003.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1051.003.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cdeb2a23fa47156bf57f7870b5d89e1e'
'b.e21.BSSP370smbb.f09_g17.LE2-1071.004.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1071.004.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8ab2639617145dfeb2cb58daf5777619'
'b.e21.BSSP370smbb.f09_g17.LE2-1091.005.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1091.005.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c8172a8ace99fddb328434d11e82a104'
'b.e21.BSSP370smbb.f09_g17.LE2-1111.006.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1111.006.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3ff900d667a69dcca4e0175ca474009a'
'b.e21.BSSP370smbb.f09_g17.LE2-1131.007.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1131.007.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2d814cd4b22275b11f04f3eb5b3dd727'
'b.e21.BSSP370smbb.f09_g17.LE2-1151.008.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1151.008.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '000584f6b226db6d66a3d32b8eb7ab30'
'b.e21.BSSP370smbb.f09_g17.LE2-1171.009.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1171.009.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '654b248fe54ab5724dd5c21fb974d240'
'b.e21.BSSP370smbb.f09_g17.LE2-1191.010.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1191.010.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2b68580775d86641b60082727abf1e88'
'b.e21.BSSP370smbb.f09_g17.LE2-1231.011.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1231.011.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c384d4056e347a527017b1cce2899d26'
'b.e21.BSSP370smbb.f09_g17.LE2-1231.012.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1231.012.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '13e559897a8442ed1b894719ddd735bd'
'b.e21.BSSP370smbb.f09_g17.LE2-1231.013.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1231.013.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3250649f5d65f10d8353629c2800e731'
'b.e21.BSSP370smbb.f09_g17.LE2-1231.014.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1231.014.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '74cd108e71302e8355edb9e0ca2761b0'
'b.e21.BSSP370smbb.f09_g17.LE2-1231.015.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1231.015.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '81f34b6ea02703a9fff9c4f08587e618'
'b.e21.BSSP370smbb.f09_g17.LE2-1231.016.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1231.016.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e2c907cb3d27b209b6c9fcab6fe6649a'
'b.e21.BSSP370smbb.f09_g17.LE2-1231.017.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1231.017.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4fa51026c30336ec984c7251590f7a04'
'b.e21.BSSP370smbb.f09_g17.LE2-1231.018.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1231.018.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f6a63cd2b8c8a541063eb40f176211ae'
'b.e21.BSSP370smbb.f09_g17.LE2-1231.019.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1231.019.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ef7dcd013026b53f5aecc02480f31288'
'b.e21.BSSP370smbb.f09_g17.LE2-1231.020.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1231.020.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '541cacb8881eb6a054a1fb39513f18df'
'b.e21.BSSP370smbb.f09_g17.LE2-1251.011.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1251.011.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1a0f6d466aa45c42bc2917984fbca56e'
'b.e21.BSSP370smbb.f09_g17.LE2-1251.012.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1251.012.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c622ec0ba2aca58223e3d3af262bcb9a'
'b.e21.BSSP370smbb.f09_g17.LE2-1251.013.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1251.013.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '430ba88f6e9c380f9312cd23c5ca4866'
'b.e21.BSSP370smbb.f09_g17.LE2-1251.014.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1251.014.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '598e28da6e56bb1b9941e2fe62555858'
'b.e21.BSSP370smbb.f09_g17.LE2-1251.015.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1251.015.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd616498dc1810dbe9c94f86a14c375f2'
'b.e21.BSSP370smbb.f09_g17.LE2-1251.016.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1251.016.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c137a27242fd2331358b86f85f274074'
'b.e21.BSSP370smbb.f09_g17.LE2-1251.017.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1251.017.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4606b850d6bc6a006237a60079032219'
'b.e21.BSSP370smbb.f09_g17.LE2-1251.018.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1251.018.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'df5d332e25b633d2b9fa5bf3c308b5f6'
'b.e21.BSSP370smbb.f09_g17.LE2-1251.019.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1251.019.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c36d85691f491079e10569fa273a8601'
'b.e21.BSSP370smbb.f09_g17.LE2-1251.020.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1251.020.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '78324dcf04f7a51aa3a198cde14094d0'
'b.e21.BSSP370smbb.f09_g17.LE2-1281.011.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1281.011.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'bb057a0eba7d888db3939ab28ed34a8d'
'b.e21.BSSP370smbb.f09_g17.LE2-1281.012.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1281.012.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd7beb29c114931e0bf09457aae115ecb'
'b.e21.BSSP370smbb.f09_g17.LE2-1281.013.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1281.013.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2cecc8413db237e6d7d09ec8e40afb25'
'b.e21.BSSP370smbb.f09_g17.LE2-1281.014.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1281.014.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b8494d7399317bf8cddede726b1fd251'
'b.e21.BSSP370smbb.f09_g17.LE2-1281.015.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1281.015.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5bcb5fe86cc1ffc250bba0770b7cedb7'
'b.e21.BSSP370smbb.f09_g17.LE2-1281.016.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1281.016.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4f610cf341ac0468c3f004420816d37f'
'b.e21.BSSP370smbb.f09_g17.LE2-1281.017.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1281.017.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9bf099c17b0a7da1ce0440e3e0eb6747'
'b.e21.BSSP370smbb.f09_g17.LE2-1281.018.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1281.018.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ab2b51c84fb49d4a0698fa4cb58f18ec'
'b.e21.BSSP370smbb.f09_g17.LE2-1281.019.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1281.019.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '774c44b89f2b3b087a15ad917ff52912'
'b.e21.BSSP370smbb.f09_g17.LE2-1281.020.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1281.020.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '15bf8f73d43ec2fb709a23aa1eac0ca1'
'b.e21.BSSP370smbb.f09_g17.LE2-1301.011.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1301.011.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '979f0732c456d9b424ee331e49d26699'
'b.e21.BSSP370smbb.f09_g17.LE2-1301.012.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1301.012.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9c2c412e75cf5a0402d0c5703fab0620'
'b.e21.BSSP370smbb.f09_g17.LE2-1301.013.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1301.013.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c13ab1cfe5295dd468e1ac012b7a7294'
'b.e21.BSSP370smbb.f09_g17.LE2-1301.014.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1301.014.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '96d0dd745f5fcab3839b58c960a7afc7'
'b.e21.BSSP370smbb.f09_g17.LE2-1301.015.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1301.015.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '292512b8c61da164419fce02042e4e1c'
'b.e21.BSSP370smbb.f09_g17.LE2-1301.016.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1301.016.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'abc25237dc8c15200abfb35796adc24b'
'b.e21.BSSP370smbb.f09_g17.LE2-1301.017.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1301.017.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7c8f8011e43a983ed350a27930c4eb7e'
'b.e21.BSSP370smbb.f09_g17.LE2-1301.018.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1301.018.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '48e679df7a70a9c5808262c09b507093'
'b.e21.BSSP370smbb.f09_g17.LE2-1301.019.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1301.019.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6a6f7d6e8bdd1f5c775a99d142202979'
'b.e21.BSSP370smbb.f09_g17.LE2-1301.020.pop.h.spChl.201501-202412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BSSP370smbb.f09_g17.LE2-1301.020.pop.h.spChl.201501-202412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f4fc730caf2965c833c6883540a50bba'
EOF--dataset.file.url.chksum_type.chksum

}


#
# MAIN
#
echo "Running $(basename $0) version: $version"

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE

download

#remove duplicates (if any)
{ rm $CACHE_FILE && tac | awk '!x[$1]++' | tac > $CACHE_FILE; } < $CACHE_FILE

