#!/bin/bash


WGET_VERSION=$(wget --version | grep -oie "wget [0-9][0-9.]*" | head -n 1 | awk '{print $2}')
if [ -z "$WGET_VERSION" ]
then
WGET_VERSION=PARSE_ERROR
fi

WGET_USER_AGENT="wget/$WGET_VERSION/esg/4.3.2-20230405-191025/created/2023-04-17T03:08:27-06:00"


##############################################################################
#
# Climate Data Gateway download script
#
#
# Generated by: NCAR Climate Data Gateway
#
# Template version: 0.4.7-wget-checksum
#
#
# Your download selection includes data that might be secured using API Token based
# authentication. Therefore, this script can have your api-token. If you
# re-generate your API Token after you download this script, the download will
# fail. If that happens, you can either re-download this script or you can replace
# the old API Token with the new one by going to the Account Home:
#
# https://www.earthsystemgrid.org/account/user/account-home.html
#
# and clicking on "API Token" link under "Personal Account". You will be asked
# to log into the application before you can view your API Token.
#
#
# Dataset
# ucar.cgd.cesm2le.ocn.proc.monthly_ave.spChl
# acc57864-9900-4fb7-a0a0-564dcdd927f4
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.ocn.proc.monthly_ave.spChl.html
# https://www.earthsystemgrid.org/dataset/id/acc57864-9900-4fb7-a0a0-564dcdd927f4.html
#
# Dataset Version
# 2
# c8d7e215-c5e7-4286-8390-617d81c3cc60
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.ocn.proc.monthly_ave.spChl/version/2.html
# https://www.earthsystemgrid.org/dataset/version/id/c8d7e215-c5e7-4286-8390-617d81c3cc60.html
#
##############################################################################

CACHE_FILE=.md5_results
MAX_RETRY=3


usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
}
#defaults
debug=0
clean_work=1
verbose=1

#parse flags

while getopts ':pdvqko:' OPT; do

    case $OPT in

        p) clean_work=0;;       #	: preserve data that failed checksum
        o) output="$OPTARG";;   #<file>	: Write output for DML in the given file
        d) debug=1;;            #	: display debug information
        v) verbose=1;;          #       : be more verbose
        q) quiet=1;;            #	: be less verbose
        k) cert=1;;            #	: add --no-check-certificate
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

if [[ "$output" ]]; then
    #check and prepare the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    : > "$output" || { echo "Can't write file $output"; break; }
fi

    ((debug)) && echo "debug=$debug, cert=$cert, verbose=$verbose, quiet=$quiet, clean_work=$clean_work"

##############################################################################


check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum

    case $chk_type in
        md5) local_chksum=$(md5sum "$file" | cut -f1 -d" ");;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value"
    diff -q <(echo $local_chksum) <(echo $chk_value) >/dev/null
}

download() {

    if [[ "$cert" ]]; then
      wget="wget --no-check-certificate -c --user-agent=$WGET_USER_AGENT"
    else
      wget="wget -c --user-agent=$WGET_USER_AGENT"
    fi

    ((quiet)) && wget="$wget -q" || { ((!verbose)) && wget="$wget -nv"; }

    ((debug)) && echo "wget command: $wget"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #are we just writing a file?
        if [ "$output" ]; then
            echo "$file - $url" >> $output
            echo ""
            continue
        fi

        retry_counter=0

        while : ; do
                #if we have the file, check if it's already processed.
                [ -f "$file" ] && cached="$(grep $file $CACHE_FILE)" || unset cached

                #check it wasn't modified
                if [[ -n "$cached" && "$(stat -c %Y $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    echo "Already downloaded and verified"
                    break
                fi

                # (if we had the file size, we could check before trying to complete)
                echo "Downloading"
                $wget -O "$file" $url || { failed=1; break; }

                #check if file is there
                if [[ -f "$file" ]]; then
                        ((debug)) && echo file found
                        if ! check_chksum "$file" $chksum_type $chksum; then
                                echo "  $chksum_type failed!"
                                if ((clean_work)); then
                                        rm "$file"

                                        #try again up to n times
                                        echo -n "  Re-downloading..."

                                        if [ $retry_counter -eq $MAX_RETRY]
                                        then
                                            echo "  Re-tried file $file $MAX_RETRY times...."
                                            break
                                        fi
                                        retry_counter=`expr $retry_counter + 1`

                                        continue
                                else
                                        echo "  don't use -p or remove manually."
                                fi
                        else
                                echo "  $chksum_type ok. done!"
                                echo "$file" $(stat -c %Y "$file") $chksum >> $CACHE_FILE
                        fi
                fi
                #done!
                break
        done

        if ((failed)); then
            echo "download failed"

            unset failed
        fi

    done <<EOF--dataset.file.url.chksum_type.chksum
'b.e21.BHISTsmbb.f09_g17.LE2-1011.001.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1011.001.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f3ba3bc641ef0fe190aeed19b9e4c213'
'b.e21.BHISTsmbb.f09_g17.LE2-1031.002.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1031.002.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6298d537f7dd110e1a302326f54380e8'
'b.e21.BHISTsmbb.f09_g17.LE2-1051.003.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1051.003.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0837ed8f5a2ea808cfca20915af6496e'
'b.e21.BHISTsmbb.f09_g17.LE2-1071.004.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1071.004.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cb8f1bcd113f4ab9d8fb468ce40f72fb'
'b.e21.BHISTsmbb.f09_g17.LE2-1091.005.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1091.005.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6538f1a2f3087152b696bb19daa75716'
'b.e21.BHISTsmbb.f09_g17.LE2-1111.006.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1111.006.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '71273c709a1029fa8f8051381581200c'
'b.e21.BHISTsmbb.f09_g17.LE2-1131.007.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1131.007.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '10ff680f39bcfefe778194e238eeb6de'
'b.e21.BHISTsmbb.f09_g17.LE2-1151.008.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1151.008.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9d8ab8c9fc94b02c4dc67d7d6eee19c7'
'b.e21.BHISTsmbb.f09_g17.LE2-1171.009.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1171.009.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cadc5d9e8da1c3d6f7702bbfec659e52'
'b.e21.BHISTsmbb.f09_g17.LE2-1191.010.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1191.010.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cb31e15a976330d0fd9905e589f541f5'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.011.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.011.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2ca999d1871e7959c1296635ea71df7c'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.012.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.012.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4c28d5b9429a57810949fb67e626c912'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.013.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.013.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3a08506e1fd85024741525403a136f37'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.014.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.014.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ca7b8de825d1fffd6ffe03471bd97248'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.015.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.015.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5bb8694da18550b6f1ee049ff42e0571'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.016.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.016.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '241b5243e610fa34bab845541429440e'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.017.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.017.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '23c3a4dc3a126bec95f5c736fd018ee8'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.018.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.018.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2bcc104cb245dd68c6231af0c40b7e66'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.019.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.019.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0ec875af2cd9a93f94bee6e2a95382c1'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.020.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.020.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cdeb440f44f4a0bb3af9901af26fe7c9'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.011.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.011.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1e0d88ed3faef1364ba7a2c37d824467'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.012.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.012.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '77828a7cb78bd84ad037448807749bf8'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.013.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.013.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6dd73a502fc26960886934e88ce85365'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.014.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.014.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '097cf59f3d777dbf1dc75c82a64badfc'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.015.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.015.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f3926a058d00d9b5496f3dc9c8b08c88'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.016.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.016.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ca1c67c13a67184513629f0291122e41'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.017.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.017.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b1a82b481ff3d46807c95c3f845f1323'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.018.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.018.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '64c06233971790c8b148749a685eb395'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.019.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.019.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2865903e7c73e9e5ec26c09485da1383'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.020.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.020.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '83b36d4d960e8f914a6c8260dd2fad53'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.011.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.011.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e18a8ac546b1c044884b1178f205ddcf'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.012.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.012.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ee18d70b49437ca1cc6278ed3c8818db'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.013.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.013.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '45ea5cee08c67d8c0b87c635e7d8d575'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.014.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.014.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '732c156ffe7cee77a22d8ff746e6993b'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.015.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.015.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a4f87cef06d303ca590fb942725ff0aa'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.016.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.016.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'bd9c877c0ff2c11673e93f10f5e01077'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.017.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.017.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9a1e2d14e6c4011546251c927ca4c47d'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.018.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.018.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e2e16828d5cc27a9334b79653fce3e2f'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.019.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.019.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '28c5087b65ca21cff6cba76d1f4728af'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.020.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.020.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cf7c9356bfd3d65496c92e8b818bd53b'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.011.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.011.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e741ab77b85406742396d601a4acd45c'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.012.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.012.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7234294b6c6e88eb23b916e021e383a2'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.013.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.013.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd7ae207c23dd180e641cbb18faa56dfa'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.014.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.014.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c2c59712992502c0839ae9078a9a0dfb'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.015.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.015.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e2d4069966c6f6896200b3aa5387a34e'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.016.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.016.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1e9d16c22d0ca3bd045c44424bcd27b7'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.017.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.017.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0580a0fb057050630caf0a967bcab250'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.018.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.018.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c2831652faad363416162aa3bd592197'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.019.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.019.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7aa72770cd9d3bcfe1ffac41766eea33'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.020.pop.h.spChl.196001-196912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.020.pop.h.spChl.196001-196912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '568bf04b62945ec12d7fe21f7a61269d'
EOF--dataset.file.url.chksum_type.chksum

}


#
# MAIN
#
echo "Running $(basename $0) version: $version"

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE

download

#remove duplicates (if any)
{ rm $CACHE_FILE && tac | awk '!x[$1]++' | tac > $CACHE_FILE; } < $CACHE_FILE
