#!/bin/bash


WGET_VERSION=$(wget --version | grep -oie "wget [0-9][0-9.]*" | head -n 1 | awk '{print $2}')
if [ -z "$WGET_VERSION" ]
then
WGET_VERSION=PARSE_ERROR
fi

WGET_USER_AGENT="wget/$WGET_VERSION/esg/4.3.2-20230405-191025/created/2023-04-17T03:08:16-06:00"


##############################################################################
#
# Climate Data Gateway download script
#
#
# Generated by: NCAR Climate Data Gateway
#
# Template version: 0.4.7-wget-checksum
#
#
# Your download selection includes data that might be secured using API Token based
# authentication. Therefore, this script can have your api-token. If you
# re-generate your API Token after you download this script, the download will
# fail. If that happens, you can either re-download this script or you can replace
# the old API Token with the new one by going to the Account Home:
#
# https://www.earthsystemgrid.org/account/user/account-home.html
#
# and clicking on "API Token" link under "Personal Account". You will be asked
# to log into the application before you can view your API Token.
#
#
# Dataset
# ucar.cgd.cesm2le.ocn.proc.monthly_ave.spChl
# acc57864-9900-4fb7-a0a0-564dcdd927f4
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.ocn.proc.monthly_ave.spChl.html
# https://www.earthsystemgrid.org/dataset/id/acc57864-9900-4fb7-a0a0-564dcdd927f4.html
#
# Dataset Version
# 2
# c8d7e215-c5e7-4286-8390-617d81c3cc60
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.ocn.proc.monthly_ave.spChl/version/2.html
# https://www.earthsystemgrid.org/dataset/version/id/c8d7e215-c5e7-4286-8390-617d81c3cc60.html
#
##############################################################################

CACHE_FILE=.md5_results
MAX_RETRY=3


usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
}
#defaults
debug=0
clean_work=1
verbose=1

#parse flags

while getopts ':pdvqko:' OPT; do

    case $OPT in

        p) clean_work=0;;       #	: preserve data that failed checksum
        o) output="$OPTARG";;   #<file>	: Write output for DML in the given file
        d) debug=1;;            #	: display debug information
        v) verbose=1;;          #       : be more verbose
        q) quiet=1;;            #	: be less verbose
        k) cert=1;;            #	: add --no-check-certificate
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

if [[ "$output" ]]; then
    #check and prepare the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    : > "$output" || { echo "Can't write file $output"; break; }
fi

    ((debug)) && echo "debug=$debug, cert=$cert, verbose=$verbose, quiet=$quiet, clean_work=$clean_work"

##############################################################################


check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum

    case $chk_type in
        md5) local_chksum=$(md5sum "$file" | cut -f1 -d" ");;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value"
    diff -q <(echo $local_chksum) <(echo $chk_value) >/dev/null
}

download() {

    if [[ "$cert" ]]; then
      wget="wget --no-check-certificate -c --user-agent=$WGET_USER_AGENT"
    else
      wget="wget -c --user-agent=$WGET_USER_AGENT"
    fi

    ((quiet)) && wget="$wget -q" || { ((!verbose)) && wget="$wget -nv"; }

    ((debug)) && echo "wget command: $wget"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #are we just writing a file?
        if [ "$output" ]; then
            echo "$file - $url" >> $output
            echo ""
            continue
        fi

        retry_counter=0

        while : ; do
                #if we have the file, check if it's already processed.
                [ -f "$file" ] && cached="$(grep $file $CACHE_FILE)" || unset cached

                #check it wasn't modified
                if [[ -n "$cached" && "$(stat -c %Y $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    echo "Already downloaded and verified"
                    break
                fi

                # (if we had the file size, we could check before trying to complete)
                echo "Downloading"
                $wget -O "$file" $url || { failed=1; break; }

                #check if file is there
                if [[ -f "$file" ]]; then
                        ((debug)) && echo file found
                        if ! check_chksum "$file" $chksum_type $chksum; then
                                echo "  $chksum_type failed!"
                                if ((clean_work)); then
                                        rm "$file"

                                        #try again up to n times
                                        echo -n "  Re-downloading..."

                                        if [ $retry_counter -eq $MAX_RETRY]
                                        then
                                            echo "  Re-tried file $file $MAX_RETRY times...."
                                            break
                                        fi
                                        retry_counter=`expr $retry_counter + 1`

                                        continue
                                else
                                        echo "  don't use -p or remove manually."
                                fi
                        else
                                echo "  $chksum_type ok. done!"
                                echo "$file" $(stat -c %Y "$file") $chksum >> $CACHE_FILE
                        fi
                fi
                #done!
                break
        done

        if ((failed)); then
            echo "download failed"

            unset failed
        fi

    done <<EOF--dataset.file.url.chksum_type.chksum
'b.e21.BHISTsmbb.f09_g17.LE2-1011.001.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1011.001.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0dfd47e6dde176d2fc5c42b4eceee780'
'b.e21.BHISTsmbb.f09_g17.LE2-1031.002.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1031.002.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'dca59abfcf7d53246af6a2b15ea6f37e'
'b.e21.BHISTsmbb.f09_g17.LE2-1051.003.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1051.003.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0f1c814d47d3fa92c9ffecd1ebd3a3b4'
'b.e21.BHISTsmbb.f09_g17.LE2-1071.004.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1071.004.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c6795cd9154e8cb98886264f6a8eb906'
'b.e21.BHISTsmbb.f09_g17.LE2-1091.005.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1091.005.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '06fe50003e4e490cc883aade4403d148'
'b.e21.BHISTsmbb.f09_g17.LE2-1111.006.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1111.006.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '08171eaefe780948949e0fc9c31b6f09'
'b.e21.BHISTsmbb.f09_g17.LE2-1131.007.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1131.007.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1c1c337155c02a1c9caf99388d7feabc'
'b.e21.BHISTsmbb.f09_g17.LE2-1151.008.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1151.008.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b72396b0fb0dd1752c5dfd6108ad3227'
'b.e21.BHISTsmbb.f09_g17.LE2-1171.009.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1171.009.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4ea14450444672ac06d35be4e08b630b'
'b.e21.BHISTsmbb.f09_g17.LE2-1191.010.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1191.010.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '142200f490372b04e6438f0244c76e36'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.011.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.011.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '948704e3b99b13e032227ebfbf72f3a4'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.012.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.012.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3a11cc33374c755b04be01043d6d7b88'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.013.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.013.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'fd7de8d87081a9953b459fae6473040e'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.014.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.014.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a1945fab1441d7681adbf0378b370ffa'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.015.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.015.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3d2b589ae7460320713fac32bd2077ff'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.016.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.016.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2caae35f0bbb75dfac201a7ebc177b27'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.017.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.017.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3c749a98972ab1e322a030c95cedc21c'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.018.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.018.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '838bd3e321f474ae13ab2cc7fceee1d3'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.019.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.019.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8bc49c67ed03c0fe3954696da7d5a53c'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.020.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.020.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ed7c1669959242f5a59de7949c8a5113'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.011.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.011.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8e21742119e3ab62a04faaed29eb3101'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.012.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.012.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'bef9ae761092b424ddb94d0e16b990db'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.013.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.013.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8b095b46ef0cb7b756bf037b24f65a30'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.014.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.014.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd570c4d3d168373b123e4ff86e604ebb'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.015.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.015.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '37e707c36ca1234ad9ff4bce9574dcc8'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.016.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.016.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '71841cf50bb28d54b72c966105d4b712'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.017.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.017.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c5c9ace70aa5cfb43a199b0463e40177'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.018.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.018.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2fe18483827f7ed87c3c5f476e1ab493'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.019.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.019.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ef9ac87fa5ca7a68b304b2d032c5de91'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.020.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.020.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '77c910f6f6d68f9d65789bf1bcedb4c2'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.011.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.011.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'edbb94505b3030802db2c76eaef40d8d'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.012.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.012.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '10cf798bd43f507e4d1b8d8bb533b582'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.013.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.013.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9f66c0943ac7dc655627e59063e49ef3'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.014.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.014.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'fe8f7208ee664a4b524aa5d20a459bad'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.015.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.015.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6ae2aaf5afc8bd725062035af48eafbd'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.016.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.016.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5a6b0188003d9317829684619b97be95'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.017.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.017.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '84468cc274f7fdbe5705fa76f473b2d8'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.018.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.018.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '87b6c087b3ab50674d6310443119754f'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.019.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.019.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5b2497666d01aefd318b72da844fef96'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.020.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.020.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2062d091df1415422fd53d56a82da301'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.011.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.011.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f1614c4f145eaba5a97ed751793299b4'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.012.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.012.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3e77d1079e25711b9ed5f7f5ad1c43c3'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.013.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.013.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '88363c005e0337cffe75970861f8d536'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.014.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.014.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '82507c57f2ef7dab11737d2f85760623'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.015.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.015.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1795ca02f9eadeae7fe1373ba414a008'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.016.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.016.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '47487652271e78005b41dd3fd7d71a4f'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.017.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.017.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2b09a08017d6be479c0563f57b743780'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.018.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.018.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0ead83327bfcac81d7f1483e7a6e89b4'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.019.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.019.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2b653e7ca5d90cc4ee24a4bf3116350c'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.020.pop.h.spChl.197001-197912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.020.pop.h.spChl.197001-197912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'dd89e4d572dd070781e57a1b7c08e317'
EOF--dataset.file.url.chksum_type.chksum

}


#
# MAIN
#
echo "Running $(basename $0) version: $version"

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE

download

#remove duplicates (if any)
{ rm $CACHE_FILE && tac | awk '!x[$1]++' | tac > $CACHE_FILE; } < $CACHE_FILE
