#!/bin/bash


WGET_VERSION=$(wget --version | grep -oie "wget [0-9][0-9.]*" | head -n 1 | awk '{print $2}')
if [ -z "$WGET_VERSION" ]
then
WGET_VERSION=PARSE_ERROR
fi

WGET_USER_AGENT="wget/$WGET_VERSION/esg/4.3.2-20230405-191025/created/2023-04-11T07:49:39-06:00"


##############################################################################
#
# Climate Data Gateway download script
#
#
# Generated by: NCAR Climate Data Gateway
#
# Template version: 0.4.7-wget-checksum
#
#
# Your download selection includes data that might be secured using API Token based
# authentication. Therefore, this script can have your api-token. If you
# re-generate your API Token after you download this script, the download will
# fail. If that happens, you can either re-download this script or you can replace
# the old API Token with the new one by going to the Account Home:
#
# https://www.earthsystemgrid.org/account/user/account-home.html
#
# and clicking on "API Token" link under "Personal Account". You will be asked
# to log into the application before you can view your API Token.
#
#
# Dataset
# ucar.cgd.cesm2le.ocn.proc.monthly_ave.spChl
# acc57864-9900-4fb7-a0a0-564dcdd927f4
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.ocn.proc.monthly_ave.spChl.html
# https://www.earthsystemgrid.org/dataset/id/acc57864-9900-4fb7-a0a0-564dcdd927f4.html
#
# Dataset Version
# 2
# c8d7e215-c5e7-4286-8390-617d81c3cc60
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.ocn.proc.monthly_ave.spChl/version/2.html
# https://www.earthsystemgrid.org/dataset/version/id/c8d7e215-c5e7-4286-8390-617d81c3cc60.html
#
##############################################################################

CACHE_FILE=.md5_results
MAX_RETRY=3


usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
}
#defaults
debug=0
clean_work=1
verbose=1

#parse flags

while getopts ':pdvqko:' OPT; do

    case $OPT in

        p) clean_work=0;;       #    : preserve data that failed checksum
        o) output="$OPTARG";;   #<file>    : Write output for DML in the given file
        d) debug=1;;            #    : display debug information
        v) verbose=1;;          #       : be more verbose
        q) quiet=1;;            #    : be less verbose
        k) cert=1;;            #    : add --no-check-certificate
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

if [[ "$output" ]]; then
    #check and prepare the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    : > "$output" || { echo "Can't write file $output"; break; }
fi

    ((debug)) && echo "debug=$debug, cert=$cert, verbose=$verbose, quiet=$quiet, clean_work=$clean_work"

##############################################################################


check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum

    case $chk_type in
        md5) local_chksum=$(md5sum "$file" | cut -f1 -d" ");;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value"
    diff -q <(echo $local_chksum) <(echo $chk_value) >/dev/null
}

download() {

    if [[ "$cert" ]]; then
      wget="wget --no-check-certificate -c --user-agent=$WGET_USER_AGENT"
    else
      wget="wget -c --user-agent=$WGET_USER_AGENT"
    fi

    ((quiet)) && wget="$wget -q" || { ((!verbose)) && wget="$wget -nv"; }

    ((debug)) && echo "wget command: $wget"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #are we just writing a file?
        if [ "$output" ]; then
            echo "$file - $url" >> $output
            echo ""
            continue
        fi

        retry_counter=0

        while : ; do
                #if we have the file, check if it's already processed.
                [ -f "$file" ] && cached="$(grep $file $CACHE_FILE)" || unset cached

                #check it wasn't modified
                if [[ -n "$cached" && "$(stat -c %Y $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    echo "Already downloaded and verified"
                    break
                fi

                # (if we had the file size, we could check before trying to complete)
                echo "Downloading"
                $wget -O "$file" $url || { failed=1; break; }

                #check if file is there
                if [[ -f "$file" ]]; then
                        ((debug)) && echo file found
                        if ! check_chksum "$file" $chksum_type $chksum; then
                                echo "  $chksum_type failed!"
                                if ((clean_work)); then
                                        rm "$file"

                                        #try again up to n times
                                        echo -n "  Re-downloading..."

                                        if [ $retry_counter -eq $MAX_RETRY]
                                        then
                                            echo "  Re-tried file $file $MAX_RETRY times...."
                                            break
                                        fi
                                        retry_counter=`expr $retry_counter + 1`

                                        continue
                                else
                                        echo "  don't use -p or remove manually."
                                fi
                        else
                                echo "  $chksum_type ok. done!"
                                echo "$file" $(stat -c %Y "$file") $chksum >> $CACHE_FILE
                        fi
                fi
                #done!
                break
        done

        if ((failed)); then
            echo "download failed"

            unset failed
        fi

    done <<EOF--dataset.file.url.chksum_type.chksum
'b.e21.BHISTcmip6.f09_g17.LE2-1001.001.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1001.001.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '28f481a6d039955c3242d45cd3d1c9e1'
'b.e21.BHISTcmip6.f09_g17.LE2-1021.002.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1021.002.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b87e741b56d0d5851c5f946b68b06c11'
'b.e21.BHISTcmip6.f09_g17.LE2-1041.003.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1041.003.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c785a2c12bd2665459169ce2e9d79c14'
'b.e21.BHISTcmip6.f09_g17.LE2-1061.004.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1061.004.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5f4277206f81e00272b15606e8ad61a9'
'b.e21.BHISTcmip6.f09_g17.LE2-1081.005.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1081.005.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ae851bec8fb99da12abfa2325dc54d2e'
'b.e21.BHISTcmip6.f09_g17.LE2-1101.006.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1101.006.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '74c7c1f2f50f6a004e4908b8a3294b39'
'b.e21.BHISTcmip6.f09_g17.LE2-1121.007.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1121.007.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c048c217fea2bf486d78a26af058f657'
'b.e21.BHISTcmip6.f09_g17.LE2-1141.008.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1141.008.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e173f795291fb841b9be7cb4106dfe06'
'b.e21.BHISTcmip6.f09_g17.LE2-1161.009.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1161.009.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '05f0b55549cfd677df0591f503dbe142'
'b.e21.BHISTcmip6.f09_g17.LE2-1181.010.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1181.010.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '84435d966813e8f370b6a63e826f49e0'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.001.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.001.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4d7aa3e80bcc160d77b5567dfa68867f'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.002.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.002.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ca819b956c9fdbc64d762ecb6416c7ad'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.003.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.003.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7368b8f06489f28da4015bbd23440457'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.004.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.004.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6a010c3054cb4dcc36a76730730fca52'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.005.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.005.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '934b53616da3c06674c6717bc9679fbc'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.006.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.006.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd952c70cf57ba695e629bc848bc04e23'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.007.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.007.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6560570ab37d944a2ec8de524daeda8a'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.008.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.008.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7e3b415e21080cec4fa9bb5ed3198802'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.009.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.009.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cd44a0dcd1c06d01687bbb927885d1c6'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.010.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.010.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '52c274adc409873b99e50e5ddfaf0b21'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.001.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.001.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a9e9105cffed2c3888dbf8d6595e40b7'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.002.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.002.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'addc84dc36820e347d8f76c16e19612d'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.003.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.003.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f602d006c089941f88eb13b642e758e7'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.004.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.004.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a707b7a44182901a4cbb2601ab5b42b7'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.005.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.005.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c6e456a8f43f473c58f27c81d098c165'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.006.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.006.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'fb6ec54e3c51293034b3af32df1dffaa'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.007.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.007.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '043f19e3fcc615c9df6b286f66fb7bc0'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.008.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.008.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '09d3df66fc0bf807d8c8e04e48191879'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.009.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.009.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a681808f3f3d587dfa781df14f1b3c8d'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.010.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.010.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e36e49f16705113ffc41ec5440aff625'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.001.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.001.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'def3af5e4ed442c3f946632a17b1c5de'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.002.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.002.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b46e6f21e06dedb9a1fc6db1015b6362'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.003.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.003.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '50f2e52b158b5261060338aec1dad72d'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.004.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.004.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b36917722f0e3c8bacfa0581770a1fe1'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.005.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.005.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c40ebde34a87ed32260bd1deb435d399'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.006.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.006.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7992fc211a51d53470abf8d642e5a9ea'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.007.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.007.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd255a499a1101c6a012f40334f626043'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.008.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.008.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cdd7e5af88724fa0dac5db641c3a7bc1'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.009.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.009.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1f09f72a3a0a6c663fe676d4aef1dd01'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.010.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.010.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a4122c67ab941de276a4dc8fde2422e1'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.001.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.001.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '845f54550e1e0ed7fc0b72a825adc83c'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.002.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.002.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a88ec21708f61b5a72ed6a0a9800f7c6'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.003.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.003.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a623f41f9dd2615f50fef1fa5eabf4ac'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.004.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.004.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '84d0e654ef719b66dff46748a4f10e6f'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.005.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.005.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b74c133e5cff6fd913a6f67113029cdc'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.006.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.006.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c1e95344520b5ba156904d1a7ebe71ad'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.007.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.007.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4ad7b726f861bfe75dd807c1cc0a82b6'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.008.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.008.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e5ab26ffa68257161717330e8f24b068'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.009.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.009.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0dd326e928fb72acee09706631326c6c'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.010.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.010.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'bafa9e357ead03b9268bd512d6229324'
'b.e21.BHISTsmbb.f09_g17.LE2-1011.001.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1011.001.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c67886126bdbd9f5984920aceffd258c'
'b.e21.BHISTsmbb.f09_g17.LE2-1031.002.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1031.002.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'fb2660b33673031df00553b5de7355d8'
'b.e21.BHISTsmbb.f09_g17.LE2-1051.003.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1051.003.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0321ea78583b0fe2c092054790ef0151'
'b.e21.BHISTsmbb.f09_g17.LE2-1071.004.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1071.004.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '999ee21dc636f5f446418a047013c9fc'
'b.e21.BHISTsmbb.f09_g17.LE2-1091.005.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1091.005.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5a0d9d2084027b5919f6a35d2e932cdd'
'b.e21.BHISTsmbb.f09_g17.LE2-1111.006.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1111.006.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a14fa521aa5ab51cacb3972a6b4a65ac'
'b.e21.BHISTsmbb.f09_g17.LE2-1131.007.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1131.007.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4c8d497616014286f3033fff0c90eab2'
'b.e21.BHISTsmbb.f09_g17.LE2-1151.008.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1151.008.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4b1f2a0f2796a84122da382dcbf9f5e4'
'b.e21.BHISTsmbb.f09_g17.LE2-1171.009.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1171.009.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '112cca1bfbe9abee28a21d886df51f11'
'b.e21.BHISTsmbb.f09_g17.LE2-1191.010.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1191.010.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '228bbc7ce07c9f225aa045ffde45ebbe'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.011.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.011.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a512a96001c86ad2e7786af35fe081f3'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.012.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.012.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f28379e6e90ed0de95f4cd51a4104b47'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.013.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.013.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '28cd785283a2aaa80d20e2f0346ae990'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.014.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.014.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '90d48aa55056e8cda3f498ccf8bc6194'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.015.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.015.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '06bb26817ea341e4fc52d61c125ef3be'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.016.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.016.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6e585e1467d25fc242d811df1cceec19'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.017.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.017.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cbbe1e28c4a4d149e3e4ea346c9d828a'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.018.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.018.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '67f0e60b683c2677ccee247c28284ea2'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.019.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.019.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '934d160ac1a865455b978465faade284'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.020.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.020.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '431dfd26ac5cbff493ad295dfbc302e5'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.011.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.011.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c2318847b068b49fbfbe65d210bb6447'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.012.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.012.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1f862558b590f0dd62863fbbbd0292b0'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.013.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.013.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4b90ed15d046f4af359ea90ad38358b4'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.014.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.014.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'bf00011c89d5660be7b977709aaeda1c'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.015.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.015.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8bd4a34b145024fced8483baa0f1f12a'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.016.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.016.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f40fffe10bba2d73e0e692c59f8742a3'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.017.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.017.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f717357cee0289fa6b7e668378b0c6cf'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.018.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.018.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2670abe261db09309e0dd848fd28b889'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.019.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.019.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a7ad7c792ba9f9a6a29e93d58cbbba8d'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.020.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.020.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7510a451b18205d38758f14ddfb2104e'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.011.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.011.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5439abe8ffd79cc746a69c54f9705ae3'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.012.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.012.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4530c04cd95e4ba6064af71ba944a1f1'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.013.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.013.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '72ba2f14d57e4dfcac4a371206ed4f4e'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.014.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.014.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e7f7b44023a52d8d5aed6b100d580a64'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.015.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.015.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '30578bd9b2a23a4f93d4576cbbcb9057'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.016.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.016.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'dc296d8c6c2e26dbe5b3d42f6334888f'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.017.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.017.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '26c73000b8a2a28fb3ce3bb2968aa66f'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.018.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.018.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '58a4d9cd1ddd3f2a055ac897b8623f4b'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.019.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.019.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '34d2e7ae40af5303c8fe3def0cad404d'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.020.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.020.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c6562c0ed82d3c0ba9f79a290025561f'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.011.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.011.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '24f6d30e5ad53d09b6c64e8c8b425da7'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.012.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.012.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1a0663f156b0bc1c42ef949cac1b6aad'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.013.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.013.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c314705e459e07a2616f3e45252c580a'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.014.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.014.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '796006486598045397c5e6b91bc48d2a'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.015.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.015.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '45ef9ae2128e6760ba4a898a1a0abc6b'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.016.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.016.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3a3b5bb31759dda51c3a938c6de9eeb8'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.017.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.017.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c4b517f78fd06ca0d250cbb51b15e15e'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.018.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.018.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a465ca6c72614692423589a940c4ad38'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.019.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.019.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'e5917e61e05e21cfaee2199c826eb568'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.020.pop.h.spChl.201001-201412.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.020.pop.h.spChl.201001-201412.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c65d6c8e1762a9ceb1c40e88a08eda60'
EOF--dataset.file.url.chksum_type.chksum

}


#
# MAIN
#
echo "Running $(basename $0) version: $version"

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE

download

#remove duplicates (if any)
{ rm $CACHE_FILE && tac | awk '!x[$1]++' | tac > $CACHE_FILE; } < $CACHE_FILE

