#!/bin/bash


WGET_VERSION=$(wget --version | grep -oie "wget [0-9][0-9.]*" | head -n 1 | awk '{print $2}')
if [ -z "$WGET_VERSION" ]
then
WGET_VERSION=PARSE_ERROR
fi

WGET_USER_AGENT="wget/$WGET_VERSION/esg/4.3.2-20230405-191025/created/2023-04-11T07:49:26-06:00"


##############################################################################
#
# Climate Data Gateway download script
#
#
# Generated by: NCAR Climate Data Gateway
#
# Template version: 0.4.7-wget-checksum
#
#
# Your download selection includes data that might be secured using API Token based
# authentication. Therefore, this script can have your api-token. If you
# re-generate your API Token after you download this script, the download will
# fail. If that happens, you can either re-download this script or you can replace
# the old API Token with the new one by going to the Account Home:
#
# https://www.earthsystemgrid.org/account/user/account-home.html
#
# and clicking on "API Token" link under "Personal Account". You will be asked
# to log into the application before you can view your API Token.
#
#
# Dataset
# ucar.cgd.cesm2le.ocn.proc.monthly_ave.spChl
# acc57864-9900-4fb7-a0a0-564dcdd927f4
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.ocn.proc.monthly_ave.spChl.html
# https://www.earthsystemgrid.org/dataset/id/acc57864-9900-4fb7-a0a0-564dcdd927f4.html
#
# Dataset Version
# 2
# c8d7e215-c5e7-4286-8390-617d81c3cc60
# https://www.earthsystemgrid.org/dataset/ucar.cgd.cesm2le.ocn.proc.monthly_ave.spChl/version/2.html
# https://www.earthsystemgrid.org/dataset/version/id/c8d7e215-c5e7-4286-8390-617d81c3cc60.html
#
##############################################################################

CACHE_FILE=.md5_results
MAX_RETRY=3


usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
}
#defaults
debug=0
clean_work=1
verbose=1

#parse flags

while getopts ':pdvqko:' OPT; do

    case $OPT in

        p) clean_work=0;;       #    : preserve data that failed checksum
        o) output="$OPTARG";;   #<file>    : Write output for DML in the given file
        d) debug=1;;            #    : display debug information
        v) verbose=1;;          #       : be more verbose
        q) quiet=1;;            #    : be less verbose
        k) cert=1;;            #    : add --no-check-certificate
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

if [[ "$output" ]]; then
    #check and prepare the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    : > "$output" || { echo "Can't write file $output"; break; }
fi

    ((debug)) && echo "debug=$debug, cert=$cert, verbose=$verbose, quiet=$quiet, clean_work=$clean_work"

##############################################################################


check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum

    case $chk_type in
        md5) local_chksum=$(md5sum "$file" | cut -f1 -d" ");;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value"
    diff -q <(echo $local_chksum) <(echo $chk_value) >/dev/null
}

download() {

    if [[ "$cert" ]]; then
      wget="wget --no-check-certificate -c --user-agent=$WGET_USER_AGENT"
    else
      wget="wget -c --user-agent=$WGET_USER_AGENT"
    fi

    ((quiet)) && wget="$wget -q" || { ((!verbose)) && wget="$wget -nv"; }

    ((debug)) && echo "wget command: $wget"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #are we just writing a file?
        if [ "$output" ]; then
            echo "$file - $url" >> $output
            echo ""
            continue
        fi

        retry_counter=0

        while : ; do
                #if we have the file, check if it's already processed.
                [ -f "$file" ] && cached="$(grep $file $CACHE_FILE)" || unset cached

                #check it wasn't modified
                if [[ -n "$cached" && "$(stat -c %Y $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    echo "Already downloaded and verified"
                    break
                fi

                # (if we had the file size, we could check before trying to complete)
                echo "Downloading"
                $wget -O "$file" $url || { failed=1; break; }

                #check if file is there
                if [[ -f "$file" ]]; then
                        ((debug)) && echo file found
                        if ! check_chksum "$file" $chksum_type $chksum; then
                                echo "  $chksum_type failed!"
                                if ((clean_work)); then
                                        rm "$file"

                                        #try again up to n times
                                        echo -n "  Re-downloading..."

                                        if [ $retry_counter -eq $MAX_RETRY]
                                        then
                                            echo "  Re-tried file $file $MAX_RETRY times...."
                                            break
                                        fi
                                        retry_counter=`expr $retry_counter + 1`

                                        continue
                                else
                                        echo "  don't use -p or remove manually."
                                fi
                        else
                                echo "  $chksum_type ok. done!"
                                echo "$file" $(stat -c %Y "$file") $chksum >> $CACHE_FILE
                        fi
                fi
                #done!
                break
        done

        if ((failed)); then
            echo "download failed"

            unset failed
        fi

    done <<EOF--dataset.file.url.chksum_type.chksum
'b.e21.BHISTcmip6.f09_g17.LE2-1001.001.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1001.001.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b9a26d48f71f6e3076d34f720f2b09a2'
'b.e21.BHISTcmip6.f09_g17.LE2-1021.002.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1021.002.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ca09f29b0ad3ea5892b553d059becf62'
'b.e21.BHISTcmip6.f09_g17.LE2-1041.003.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1041.003.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd21f7b728dd982810bb3a90d9dcaa283'
'b.e21.BHISTcmip6.f09_g17.LE2-1061.004.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1061.004.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ffbb895d3daf1dd82735ea15768d6cca'
'b.e21.BHISTcmip6.f09_g17.LE2-1081.005.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1081.005.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c7c175bef81c369624b221286a5a54e8'
'b.e21.BHISTcmip6.f09_g17.LE2-1101.006.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1101.006.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b3f313cf8cc8d0a11a36cca6f123f472'
'b.e21.BHISTcmip6.f09_g17.LE2-1121.007.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1121.007.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a860054ba05a45f936c89529f666d41b'
'b.e21.BHISTcmip6.f09_g17.LE2-1141.008.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1141.008.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8a3f297681df39b7ebc99299604403f0'
'b.e21.BHISTcmip6.f09_g17.LE2-1161.009.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1161.009.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4f022a5c17d3bcb82642885c8b5783a4'
'b.e21.BHISTcmip6.f09_g17.LE2-1181.010.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1181.010.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f03362e61c5c2febf6aade8f9bcfdf97'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.001.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.001.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd801d0f275430d337c1907e5f59a51dd'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.002.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.002.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2e79404626b476084164cddc3c0f6c95'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.003.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.003.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0b2a624eb4a9ac4940323274306edff6'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.004.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.004.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '62298da3c32d487602ab6a473db908f4'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.005.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.005.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ad226bf828215b15176045e7dfe735e1'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.006.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.006.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'fbce4e696a1ca8829a2a0fd92d13885f'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.007.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.007.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '16e9d340bfb11a8b5f8a43b912ea3ac8'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.008.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.008.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3a1190fe57994737f6185757ebf20b74'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.009.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.009.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8c8c437dd58c9e54d441efe9cde66c62'
'b.e21.BHISTcmip6.f09_g17.LE2-1231.010.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1231.010.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1d6b8b268bebfdb969a0bd5706f0b241'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.001.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.001.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '474be6ef72c531caef03341c07b92f8e'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.002.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.002.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1c42bd8d9fd2ccccb1353f968f118ea9'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.003.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.003.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7980108d5d95a1416593dfa94396e9b8'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.004.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.004.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '3ee93a8207a1976662a794b3435708cb'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.005.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.005.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ace47f8f1f0e02435799fcea091ef067'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.006.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.006.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '803586bf7b6c5e5787936e700d4db929'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.007.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.007.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cca90d1b853f4297aa5a8aadac8fbcce'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.008.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.008.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f7b7e166e0680dcd4d1819786e13b600'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.009.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.009.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '5a5a1fd65299ea3132149239525891ab'
'b.e21.BHISTcmip6.f09_g17.LE2-1251.010.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1251.010.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '966e8132c8164f2bd01712cbfd75411a'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.001.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.001.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '239e947d2ff9de789c209ca40cf5ffba'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.002.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.002.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9183f8378a4de3653e0727092cd280dd'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.003.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.003.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0d184f0bc4c2f903de2a66a5c7e6029e'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.004.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.004.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0792cca6483dda87ae212cadfda44917'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.005.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.005.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b09ceca6ee600598eff0c826c902ccec'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.006.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.006.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'f40e7d56c5cd3866c7c213a978e036ef'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.007.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.007.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '1f52f0cd0488095cd77972b69bba302a'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.008.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.008.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '06e5baf1e78d475dd9b2ad504122bf01'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.009.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.009.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b95817e56c9e934c48d960bdec901b00'
'b.e21.BHISTcmip6.f09_g17.LE2-1281.010.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1281.010.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2f1c3c720d2260bed96dc033892df71e'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.001.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.001.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c1b945d6a32e77036fb9b2a91416a97c'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.002.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.002.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '81ae77fc627ce5b38f6ae955e5d812bd'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.003.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.003.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2425f476313f834cf3b9c71edd8e51a0'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.004.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.004.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7ce86df3ea1ceeabb06501f7e7184dd1'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.005.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.005.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '124a5367a8a0b5578aae12bc4160a200'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.006.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.006.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'bf137a29e8719ebb7424385b287c76ee'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.007.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.007.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '45428a302b7681ff8272c84659202580'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.008.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.008.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '56f6bf06618af3c0dc744021a7ab3031'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.009.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.009.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '29d954ffea208055b07c9a45f26d788d'
'b.e21.BHISTcmip6.f09_g17.LE2-1301.010.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTcmip6.f09_g17.LE2-1301.010.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c266579e30ebf2713246833b6c508a25'
'b.e21.BHISTsmbb.f09_g17.LE2-1011.001.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1011.001.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '81fa4a73337d7fbf3018f856da61ef8d'
'b.e21.BHISTsmbb.f09_g17.LE2-1031.002.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1031.002.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '450c5974fb03de5460e5690ec37dcc1a'
'b.e21.BHISTsmbb.f09_g17.LE2-1051.003.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1051.003.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7717da30ef097cbe1c772b48ed99bf34'
'b.e21.BHISTsmbb.f09_g17.LE2-1071.004.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1071.004.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '9d1c21cb93fa11a145876200d55e6b76'
'b.e21.BHISTsmbb.f09_g17.LE2-1091.005.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1091.005.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'efb13fed5f0e64cdef5df089cec22f5a'
'b.e21.BHISTsmbb.f09_g17.LE2-1111.006.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1111.006.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '6563badb4c9a27d2021830da4c543d88'
'b.e21.BHISTsmbb.f09_g17.LE2-1131.007.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1131.007.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd834b9b3fcbe27044fa1a40ed6e3c436'
'b.e21.BHISTsmbb.f09_g17.LE2-1151.008.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1151.008.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cf86115e68119acfbedfde2d34c57682'
'b.e21.BHISTsmbb.f09_g17.LE2-1171.009.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1171.009.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '505efbf64e973a78eae531a128757fe6'
'b.e21.BHISTsmbb.f09_g17.LE2-1191.010.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1191.010.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '50912b25094d5d21747067c7537986e8'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.011.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.011.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c60c74e61693328388cabbce924330b1'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.012.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.012.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c2fb6cff745231c93bd53207b7fe9e54'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.013.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.013.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '458717467718938ce36f080edc11805c'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.014.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.014.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8840fa92f97f7d1effbc6ff9758cc4e7'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.015.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.015.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '2ff04f567219e886052c60ce82adda33'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.016.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.016.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '09a993321f19f51c0ceeadb202156d76'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.017.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.017.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '71598887373d4cdf778d53868fd3e378'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.018.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.018.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4bd7569fe122620aad52ff7b4ed69a51'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.019.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.019.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0eabe8778ac5e3c278189c703e1b2f3c'
'b.e21.BHISTsmbb.f09_g17.LE2-1231.020.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1231.020.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'bfd442376b0d458dc63cfb5886a707b7'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.011.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.011.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8eaf8543b64885ad69c0d8e2d815b8a2'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.012.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.012.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c0ace47f33f8fac86efbbc5ccb7f43ef'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.013.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.013.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '83c0c9c34a3e5d1cd137e2af0a30471f'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.014.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.014.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'cdacce21f6ffdb1738235d93d3bee369'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.015.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.015.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '628c11243cc24f47e213575709f50a9a'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.016.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.016.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b6a800ef04823b365bde84bb53e8e5e2'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.017.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.017.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8b83bef957d669075c6e4ee8bd9dd600'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.018.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.018.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '22b72b2e79bd829f050023a889bd29e6'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.019.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.019.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '8667c5ff6011d60981a5779610768804'
'b.e21.BHISTsmbb.f09_g17.LE2-1251.020.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1251.020.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'a4162229cb198548a5f4151c53d680e2'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.011.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.011.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '0610f253ec3d2d987b035b994e84a1d0'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.012.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.012.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'd72a3dd90a9b8fe8220ae10d2ed9252c'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.013.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.013.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'bee9b78c5e1517e44d5a8a53460270a4'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.014.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.014.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '950abb132f2f64a02cd4806bb35b0b11'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.015.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.015.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ff195c0ea24dccea0835de2199036bd0'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.016.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.016.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '131076acd0225f069b220446605d4668'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.017.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.017.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'b31b11e58f51833b0c84c0c4dba8079d'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.018.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.018.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '19b9612ef029e2e85ea370040f79d065'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.019.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.019.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4c54d495b71f3c987548ab20cdf213cf'
'b.e21.BHISTsmbb.f09_g17.LE2-1281.020.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1281.020.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'be1b78ee246e41cca12cda5edffdc966'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.011.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.011.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '7857aaa8b6bae66cf2c73ba6c60f9fed'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.012.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.012.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '74c6e0126f1c50fe653c4c0ed2e8326f'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.013.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.013.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'c516940cf0c92aa8be2b8f3d5351b1cb'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.014.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.014.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'fa244752c80f47e1d3bb5cca5c20378b'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.015.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.015.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'be645200a4f4e51d622559670c116c01'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.016.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.016.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ce29a3c0349a4f69e6cfaf3c0814b9b9'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.017.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.017.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'ea9ef22bc5e51debf3012ff99400af33'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.018.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.018.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '69ae5909a3006e9114d2054b51954566'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.019.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.019.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' '4fee9beb07f6c6cd51401a1069d311fc'
'b.e21.BHISTsmbb.f09_g17.LE2-1301.020.pop.h.spChl.200001-200912.nc' 'https://tds.ucar.edu/thredds/fileServer/datazone/campaign/cgd/cesm/CESM2-LE/ocn/proc/tseries/month_1/spChl/b.e21.BHISTsmbb.f09_g17.LE2-1301.020.pop.h.spChl.200001-200912.nc?api-token=rGm6qassoHPSNY2Do3g3b5FBW0wVopaw3nbMvpW0' 'md5' 'efc04e6eef398dd8aac05a18860035c0'
EOF--dataset.file.url.chksum_type.chksum

}


#
# MAIN
#
echo "Running $(basename $0) version: $version"

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE

download

#remove duplicates (if any)
{ rm $CACHE_FILE && tac | awk '!x[$1]++' | tac > $CACHE_FILE; } < $CACHE_FILE

